// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	api "github.com/enbility/spine-go/api"
	mock "github.com/stretchr/testify/mock"

	model "github.com/enbility/spine-go/model"
)

// BindingManagerInterface is an autogenerated mock type for the BindingManagerInterface type
type BindingManagerInterface struct {
	mock.Mock
}

type BindingManagerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *BindingManagerInterface) EXPECT() *BindingManagerInterface_Expecter {
	return &BindingManagerInterface_Expecter{mock: &_m.Mock}
}

// AddBinding provides a mock function with given fields: remoteDevice, data
func (_m *BindingManagerInterface) AddBinding(remoteDevice api.DeviceRemoteInterface, data model.BindingManagementRequestCallType) error {
	ret := _m.Called(remoteDevice, data)

	if len(ret) == 0 {
		panic("no return value specified for AddBinding")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(api.DeviceRemoteInterface, model.BindingManagementRequestCallType) error); ok {
		r0 = rf(remoteDevice, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BindingManagerInterface_AddBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBinding'
type BindingManagerInterface_AddBinding_Call struct {
	*mock.Call
}

// AddBinding is a helper method to define mock.On call
//   - remoteDevice api.DeviceRemoteInterface
//   - data model.BindingManagementRequestCallType
func (_e *BindingManagerInterface_Expecter) AddBinding(remoteDevice interface{}, data interface{}) *BindingManagerInterface_AddBinding_Call {
	return &BindingManagerInterface_AddBinding_Call{Call: _e.mock.On("AddBinding", remoteDevice, data)}
}

func (_c *BindingManagerInterface_AddBinding_Call) Run(run func(remoteDevice api.DeviceRemoteInterface, data model.BindingManagementRequestCallType)) *BindingManagerInterface_AddBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.DeviceRemoteInterface), args[1].(model.BindingManagementRequestCallType))
	})
	return _c
}

func (_c *BindingManagerInterface_AddBinding_Call) Return(_a0 error) *BindingManagerInterface_AddBinding_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BindingManagerInterface_AddBinding_Call) RunAndReturn(run func(api.DeviceRemoteInterface, model.BindingManagementRequestCallType) error) *BindingManagerInterface_AddBinding_Call {
	_c.Call.Return(run)
	return _c
}

// BindingsForFeatureAddress provides a mock function with given fields: localAddress
func (_m *BindingManagerInterface) BindingsForFeatureAddress(localAddress model.FeatureAddressType) []model.BindingManagementEntryDataType {
	ret := _m.Called(localAddress)

	if len(ret) == 0 {
		panic("no return value specified for BindingsForFeatureAddress")
	}

	var r0 []model.BindingManagementEntryDataType
	if rf, ok := ret.Get(0).(func(model.FeatureAddressType) []model.BindingManagementEntryDataType); ok {
		r0 = rf(localAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BindingManagementEntryDataType)
		}
	}

	return r0
}

// BindingManagerInterface_BindingsForFeatureAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindingsForFeatureAddress'
type BindingManagerInterface_BindingsForFeatureAddress_Call struct {
	*mock.Call
}

// BindingsForFeatureAddress is a helper method to define mock.On call
//   - localAddress model.FeatureAddressType
func (_e *BindingManagerInterface_Expecter) BindingsForFeatureAddress(localAddress interface{}) *BindingManagerInterface_BindingsForFeatureAddress_Call {
	return &BindingManagerInterface_BindingsForFeatureAddress_Call{Call: _e.mock.On("BindingsForFeatureAddress", localAddress)}
}

func (_c *BindingManagerInterface_BindingsForFeatureAddress_Call) Run(run func(localAddress model.FeatureAddressType)) *BindingManagerInterface_BindingsForFeatureAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.FeatureAddressType))
	})
	return _c
}

func (_c *BindingManagerInterface_BindingsForFeatureAddress_Call) Return(_a0 []model.BindingManagementEntryDataType) *BindingManagerInterface_BindingsForFeatureAddress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BindingManagerInterface_BindingsForFeatureAddress_Call) RunAndReturn(run func(model.FeatureAddressType) []model.BindingManagementEntryDataType) *BindingManagerInterface_BindingsForFeatureAddress_Call {
	_c.Call.Return(run)
	return _c
}

// BindingsForRemoteDevice provides a mock function with given fields: remoteDevice
func (_m *BindingManagerInterface) BindingsForRemoteDevice(remoteDevice api.DeviceRemoteInterface) []model.BindingManagementEntryDataType {
	ret := _m.Called(remoteDevice)

	if len(ret) == 0 {
		panic("no return value specified for BindingsForRemoteDevice")
	}

	var r0 []model.BindingManagementEntryDataType
	if rf, ok := ret.Get(0).(func(api.DeviceRemoteInterface) []model.BindingManagementEntryDataType); ok {
		r0 = rf(remoteDevice)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BindingManagementEntryDataType)
		}
	}

	return r0
}

// BindingManagerInterface_BindingsForRemoteDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindingsForRemoteDevice'
type BindingManagerInterface_BindingsForRemoteDevice_Call struct {
	*mock.Call
}

// BindingsForRemoteDevice is a helper method to define mock.On call
//   - remoteDevice api.DeviceRemoteInterface
func (_e *BindingManagerInterface_Expecter) BindingsForRemoteDevice(remoteDevice interface{}) *BindingManagerInterface_BindingsForRemoteDevice_Call {
	return &BindingManagerInterface_BindingsForRemoteDevice_Call{Call: _e.mock.On("BindingsForRemoteDevice", remoteDevice)}
}

func (_c *BindingManagerInterface_BindingsForRemoteDevice_Call) Run(run func(remoteDevice api.DeviceRemoteInterface)) *BindingManagerInterface_BindingsForRemoteDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.DeviceRemoteInterface))
	})
	return _c
}

func (_c *BindingManagerInterface_BindingsForRemoteDevice_Call) Return(_a0 []model.BindingManagementEntryDataType) *BindingManagerInterface_BindingsForRemoteDevice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BindingManagerInterface_BindingsForRemoteDevice_Call) RunAndReturn(run func(api.DeviceRemoteInterface) []model.BindingManagementEntryDataType) *BindingManagerInterface_BindingsForRemoteDevice_Call {
	_c.Call.Return(run)
	return _c
}

// HasBinding provides a mock function with given fields: clientAddress, serverAddress
func (_m *BindingManagerInterface) HasBinding(clientAddress *model.FeatureAddressType, serverAddress *model.FeatureAddressType) bool {
	ret := _m.Called(clientAddress, serverAddress)

	if len(ret) == 0 {
		panic("no return value specified for HasBinding")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*model.FeatureAddressType, *model.FeatureAddressType) bool); ok {
		r0 = rf(clientAddress, serverAddress)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// BindingManagerInterface_HasBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasBinding'
type BindingManagerInterface_HasBinding_Call struct {
	*mock.Call
}

// HasBinding is a helper method to define mock.On call
//   - clientAddress *model.FeatureAddressType
//   - serverAddress *model.FeatureAddressType
func (_e *BindingManagerInterface_Expecter) HasBinding(clientAddress interface{}, serverAddress interface{}) *BindingManagerInterface_HasBinding_Call {
	return &BindingManagerInterface_HasBinding_Call{Call: _e.mock.On("HasBinding", clientAddress, serverAddress)}
}

func (_c *BindingManagerInterface_HasBinding_Call) Run(run func(clientAddress *model.FeatureAddressType, serverAddress *model.FeatureAddressType)) *BindingManagerInterface_HasBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.FeatureAddressType), args[1].(*model.FeatureAddressType))
	})
	return _c
}

func (_c *BindingManagerInterface_HasBinding_Call) Return(_a0 bool) *BindingManagerInterface_HasBinding_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BindingManagerInterface_HasBinding_Call) RunAndReturn(run func(*model.FeatureAddressType, *model.FeatureAddressType) bool) *BindingManagerInterface_HasBinding_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveBinding provides a mock function with given fields: remoteDevice, data
func (_m *BindingManagerInterface) RemoveBinding(remoteDevice api.DeviceRemoteInterface, data model.BindingManagementDeleteCallType) error {
	ret := _m.Called(remoteDevice, data)

	if len(ret) == 0 {
		panic("no return value specified for RemoveBinding")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(api.DeviceRemoteInterface, model.BindingManagementDeleteCallType) error); ok {
		r0 = rf(remoteDevice, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BindingManagerInterface_RemoveBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveBinding'
type BindingManagerInterface_RemoveBinding_Call struct {
	*mock.Call
}

// RemoveBinding is a helper method to define mock.On call
//   - remoteDevice api.DeviceRemoteInterface
//   - data model.BindingManagementDeleteCallType
func (_e *BindingManagerInterface_Expecter) RemoveBinding(remoteDevice interface{}, data interface{}) *BindingManagerInterface_RemoveBinding_Call {
	return &BindingManagerInterface_RemoveBinding_Call{Call: _e.mock.On("RemoveBinding", remoteDevice, data)}
}

func (_c *BindingManagerInterface_RemoveBinding_Call) Run(run func(remoteDevice api.DeviceRemoteInterface, data model.BindingManagementDeleteCallType)) *BindingManagerInterface_RemoveBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.DeviceRemoteInterface), args[1].(model.BindingManagementDeleteCallType))
	})
	return _c
}

func (_c *BindingManagerInterface_RemoveBinding_Call) Return(_a0 error) *BindingManagerInterface_RemoveBinding_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BindingManagerInterface_RemoveBinding_Call) RunAndReturn(run func(api.DeviceRemoteInterface, model.BindingManagementDeleteCallType) error) *BindingManagerInterface_RemoveBinding_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveBindingsForLocalEntity provides a mock function with given fields: localEntity
func (_m *BindingManagerInterface) RemoveBindingsForLocalEntity(localEntity api.EntityLocalInterface) {
	_m.Called(localEntity)
}

// BindingManagerInterface_RemoveBindingsForLocalEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveBindingsForLocalEntity'
type BindingManagerInterface_RemoveBindingsForLocalEntity_Call struct {
	*mock.Call
}

// RemoveBindingsForLocalEntity is a helper method to define mock.On call
//   - localEntity api.EntityLocalInterface
func (_e *BindingManagerInterface_Expecter) RemoveBindingsForLocalEntity(localEntity interface{}) *BindingManagerInterface_RemoveBindingsForLocalEntity_Call {
	return &BindingManagerInterface_RemoveBindingsForLocalEntity_Call{Call: _e.mock.On("RemoveBindingsForLocalEntity", localEntity)}
}

func (_c *BindingManagerInterface_RemoveBindingsForLocalEntity_Call) Run(run func(localEntity api.EntityLocalInterface)) *BindingManagerInterface_RemoveBindingsForLocalEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EntityLocalInterface))
	})
	return _c
}

func (_c *BindingManagerInterface_RemoveBindingsForLocalEntity_Call) Return() *BindingManagerInterface_RemoveBindingsForLocalEntity_Call {
	_c.Call.Return()
	return _c
}

func (_c *BindingManagerInterface_RemoveBindingsForLocalEntity_Call) RunAndReturn(run func(api.EntityLocalInterface)) *BindingManagerInterface_RemoveBindingsForLocalEntity_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveBindingsForRemoteDevice provides a mock function with given fields: remoteDevice
func (_m *BindingManagerInterface) RemoveBindingsForRemoteDevice(remoteDevice api.DeviceRemoteInterface) {
	_m.Called(remoteDevice)
}

// BindingManagerInterface_RemoveBindingsForRemoteDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveBindingsForRemoteDevice'
type BindingManagerInterface_RemoveBindingsForRemoteDevice_Call struct {
	*mock.Call
}

// RemoveBindingsForRemoteDevice is a helper method to define mock.On call
//   - remoteDevice api.DeviceRemoteInterface
func (_e *BindingManagerInterface_Expecter) RemoveBindingsForRemoteDevice(remoteDevice interface{}) *BindingManagerInterface_RemoveBindingsForRemoteDevice_Call {
	return &BindingManagerInterface_RemoveBindingsForRemoteDevice_Call{Call: _e.mock.On("RemoveBindingsForRemoteDevice", remoteDevice)}
}

func (_c *BindingManagerInterface_RemoveBindingsForRemoteDevice_Call) Run(run func(remoteDevice api.DeviceRemoteInterface)) *BindingManagerInterface_RemoveBindingsForRemoteDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.DeviceRemoteInterface))
	})
	return _c
}

func (_c *BindingManagerInterface_RemoveBindingsForRemoteDevice_Call) Return() *BindingManagerInterface_RemoveBindingsForRemoteDevice_Call {
	_c.Call.Return()
	return _c
}

func (_c *BindingManagerInterface_RemoveBindingsForRemoteDevice_Call) RunAndReturn(run func(api.DeviceRemoteInterface)) *BindingManagerInterface_RemoveBindingsForRemoteDevice_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveBindingsForRemoteEntity provides a mock function with given fields: remoteEntity
func (_m *BindingManagerInterface) RemoveBindingsForRemoteEntity(remoteEntity api.EntityRemoteInterface) {
	_m.Called(remoteEntity)
}

// BindingManagerInterface_RemoveBindingsForRemoteEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveBindingsForRemoteEntity'
type BindingManagerInterface_RemoveBindingsForRemoteEntity_Call struct {
	*mock.Call
}

// RemoveBindingsForRemoteEntity is a helper method to define mock.On call
//   - remoteEntity api.EntityRemoteInterface
func (_e *BindingManagerInterface_Expecter) RemoveBindingsForRemoteEntity(remoteEntity interface{}) *BindingManagerInterface_RemoveBindingsForRemoteEntity_Call {
	return &BindingManagerInterface_RemoveBindingsForRemoteEntity_Call{Call: _e.mock.On("RemoveBindingsForRemoteEntity", remoteEntity)}
}

func (_c *BindingManagerInterface_RemoveBindingsForRemoteEntity_Call) Run(run func(remoteEntity api.EntityRemoteInterface)) *BindingManagerInterface_RemoveBindingsForRemoteEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EntityRemoteInterface))
	})
	return _c
}

func (_c *BindingManagerInterface_RemoveBindingsForRemoteEntity_Call) Return() *BindingManagerInterface_RemoveBindingsForRemoteEntity_Call {
	_c.Call.Return()
	return _c
}

func (_c *BindingManagerInterface_RemoveBindingsForRemoteEntity_Call) RunAndReturn(run func(api.EntityRemoteInterface)) *BindingManagerInterface_RemoveBindingsForRemoteEntity_Call {
	_c.Call.Return(run)
	return _c
}

// NewBindingManagerInterface creates a new instance of BindingManagerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBindingManagerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BindingManagerInterface {
	mock := &BindingManagerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
