// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	model "github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// ComControl is an autogenerated mock type for the ComControl type
type ComControl struct {
	mock.Mock
}

type ComControl_Expecter struct {
	mock *mock.Mock
}

func (_m *ComControl) EXPECT() *ComControl_Expecter {
	return &ComControl_Expecter{mock: &_m.Mock}
}

// SendSpineMessage provides a mock function with given fields: datagram
func (_m *ComControl) SendSpineMessage(datagram model.DatagramType) error {
	ret := _m.Called(datagram)

	if len(ret) == 0 {
		panic("no return value specified for SendSpineMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.DatagramType) error); ok {
		r0 = rf(datagram)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ComControl_SendSpineMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendSpineMessage'
type ComControl_SendSpineMessage_Call struct {
	*mock.Call
}

// SendSpineMessage is a helper method to define mock.On call
//   - datagram model.DatagramType
func (_e *ComControl_Expecter) SendSpineMessage(datagram interface{}) *ComControl_SendSpineMessage_Call {
	return &ComControl_SendSpineMessage_Call{Call: _e.mock.On("SendSpineMessage", datagram)}
}

func (_c *ComControl_SendSpineMessage_Call) Run(run func(datagram model.DatagramType)) *ComControl_SendSpineMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.DatagramType))
	})
	return _c
}

func (_c *ComControl_SendSpineMessage_Call) Return(_a0 error) *ComControl_SendSpineMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ComControl_SendSpineMessage_Call) RunAndReturn(run func(model.DatagramType) error) *ComControl_SendSpineMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewComControl creates a new instance of ComControl. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewComControl(t interface {
	mock.TestingT
	Cleanup(func())
}) *ComControl {
	mock := &ComControl{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
