// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewDeviceInterface creates a new instance of DeviceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeviceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeviceInterface {
	mock := &DeviceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DeviceInterface is an autogenerated mock type for the DeviceInterface type
type DeviceInterface struct {
	mock.Mock
}

type DeviceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *DeviceInterface) EXPECT() *DeviceInterface_Expecter {
	return &DeviceInterface_Expecter{mock: &_m.Mock}
}

// Address provides a mock function for the type DeviceInterface
func (_mock *DeviceInterface) Address() *model.AddressDeviceType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 *model.AddressDeviceType
	if returnFunc, ok := ret.Get(0).(func() *model.AddressDeviceType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AddressDeviceType)
		}
	}
	return r0
}

// DeviceInterface_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type DeviceInterface_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *DeviceInterface_Expecter) Address() *DeviceInterface_Address_Call {
	return &DeviceInterface_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *DeviceInterface_Address_Call) Run(run func()) *DeviceInterface_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DeviceInterface_Address_Call) Return(addressDeviceType *model.AddressDeviceType) *DeviceInterface_Address_Call {
	_c.Call.Return(addressDeviceType)
	return _c
}

func (_c *DeviceInterface_Address_Call) RunAndReturn(run func() *model.AddressDeviceType) *DeviceInterface_Address_Call {
	_c.Call.Return(run)
	return _c
}

// DestinationData provides a mock function for the type DeviceInterface
func (_mock *DeviceInterface) DestinationData() model.NodeManagementDestinationDataType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DestinationData")
	}

	var r0 model.NodeManagementDestinationDataType
	if returnFunc, ok := ret.Get(0).(func() model.NodeManagementDestinationDataType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(model.NodeManagementDestinationDataType)
	}
	return r0
}

// DeviceInterface_DestinationData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DestinationData'
type DeviceInterface_DestinationData_Call struct {
	*mock.Call
}

// DestinationData is a helper method to define mock.On call
func (_e *DeviceInterface_Expecter) DestinationData() *DeviceInterface_DestinationData_Call {
	return &DeviceInterface_DestinationData_Call{Call: _e.mock.On("DestinationData")}
}

func (_c *DeviceInterface_DestinationData_Call) Run(run func()) *DeviceInterface_DestinationData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DeviceInterface_DestinationData_Call) Return(nodeManagementDestinationDataType model.NodeManagementDestinationDataType) *DeviceInterface_DestinationData_Call {
	_c.Call.Return(nodeManagementDestinationDataType)
	return _c
}

func (_c *DeviceInterface_DestinationData_Call) RunAndReturn(run func() model.NodeManagementDestinationDataType) *DeviceInterface_DestinationData_Call {
	_c.Call.Return(run)
	return _c
}

// DeviceType provides a mock function for the type DeviceInterface
func (_mock *DeviceInterface) DeviceType() *model.DeviceTypeType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeviceType")
	}

	var r0 *model.DeviceTypeType
	if returnFunc, ok := ret.Get(0).(func() *model.DeviceTypeType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DeviceTypeType)
		}
	}
	return r0
}

// DeviceInterface_DeviceType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeviceType'
type DeviceInterface_DeviceType_Call struct {
	*mock.Call
}

// DeviceType is a helper method to define mock.On call
func (_e *DeviceInterface_Expecter) DeviceType() *DeviceInterface_DeviceType_Call {
	return &DeviceInterface_DeviceType_Call{Call: _e.mock.On("DeviceType")}
}

func (_c *DeviceInterface_DeviceType_Call) Run(run func()) *DeviceInterface_DeviceType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DeviceInterface_DeviceType_Call) Return(deviceTypeType *model.DeviceTypeType) *DeviceInterface_DeviceType_Call {
	_c.Call.Return(deviceTypeType)
	return _c
}

func (_c *DeviceInterface_DeviceType_Call) RunAndReturn(run func() *model.DeviceTypeType) *DeviceInterface_DeviceType_Call {
	_c.Call.Return(run)
	return _c
}

// FeatureSet provides a mock function for the type DeviceInterface
func (_mock *DeviceInterface) FeatureSet() *model.NetworkManagementFeatureSetType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FeatureSet")
	}

	var r0 *model.NetworkManagementFeatureSetType
	if returnFunc, ok := ret.Get(0).(func() *model.NetworkManagementFeatureSetType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.NetworkManagementFeatureSetType)
		}
	}
	return r0
}

// DeviceInterface_FeatureSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FeatureSet'
type DeviceInterface_FeatureSet_Call struct {
	*mock.Call
}

// FeatureSet is a helper method to define mock.On call
func (_e *DeviceInterface_Expecter) FeatureSet() *DeviceInterface_FeatureSet_Call {
	return &DeviceInterface_FeatureSet_Call{Call: _e.mock.On("FeatureSet")}
}

func (_c *DeviceInterface_FeatureSet_Call) Run(run func()) *DeviceInterface_FeatureSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DeviceInterface_FeatureSet_Call) Return(networkManagementFeatureSetType *model.NetworkManagementFeatureSetType) *DeviceInterface_FeatureSet_Call {
	_c.Call.Return(networkManagementFeatureSetType)
	return _c
}

func (_c *DeviceInterface_FeatureSet_Call) RunAndReturn(run func() *model.NetworkManagementFeatureSetType) *DeviceInterface_FeatureSet_Call {
	_c.Call.Return(run)
	return _c
}
