// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	api "github.com/enbility/spine-go/api"
	mock "github.com/stretchr/testify/mock"
)

// EventHandler is an autogenerated mock type for the EventHandler type
type EventHandler struct {
	mock.Mock
}

type EventHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *EventHandler) EXPECT() *EventHandler_Expecter {
	return &EventHandler_Expecter{mock: &_m.Mock}
}

// HandleEvent provides a mock function with given fields: _a0
func (_m *EventHandler) HandleEvent(_a0 api.EventPayload) {
	_m.Called(_a0)
}

// EventHandler_HandleEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleEvent'
type EventHandler_HandleEvent_Call struct {
	*mock.Call
}

// HandleEvent is a helper method to define mock.On call
//   - _a0 api.EventPayload
func (_e *EventHandler_Expecter) HandleEvent(_a0 interface{}) *EventHandler_HandleEvent_Call {
	return &EventHandler_HandleEvent_Call{Call: _e.mock.On("HandleEvent", _a0)}
}

func (_c *EventHandler_HandleEvent_Call) Run(run func(_a0 api.EventPayload)) *EventHandler_HandleEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EventPayload))
	})
	return _c
}

func (_c *EventHandler_HandleEvent_Call) Return() *EventHandler_HandleEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventHandler_HandleEvent_Call) RunAndReturn(run func(api.EventPayload)) *EventHandler_HandleEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventHandler creates a new instance of EventHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventHandler {
	mock := &EventHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
