// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	api "github.com/enbility/spine-go/api"
	mock "github.com/stretchr/testify/mock"
)

// FeatureResultInterface is an autogenerated mock type for the FeatureResultInterface type
type FeatureResultInterface struct {
	mock.Mock
}

type FeatureResultInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *FeatureResultInterface) EXPECT() *FeatureResultInterface_Expecter {
	return &FeatureResultInterface_Expecter{mock: &_m.Mock}
}

// HandleResult provides a mock function with given fields: _a0
func (_m *FeatureResultInterface) HandleResult(_a0 api.ResultMessage) {
	_m.Called(_a0)
}

// FeatureResultInterface_HandleResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleResult'
type FeatureResultInterface_HandleResult_Call struct {
	*mock.Call
}

// HandleResult is a helper method to define mock.On call
//   - _a0 api.ResultMessage
func (_e *FeatureResultInterface_Expecter) HandleResult(_a0 interface{}) *FeatureResultInterface_HandleResult_Call {
	return &FeatureResultInterface_HandleResult_Call{Call: _e.mock.On("HandleResult", _a0)}
}

func (_c *FeatureResultInterface_HandleResult_Call) Run(run func(_a0 api.ResultMessage)) *FeatureResultInterface_HandleResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.ResultMessage))
	})
	return _c
}

func (_c *FeatureResultInterface_HandleResult_Call) Return() *FeatureResultInterface_HandleResult_Call {
	_c.Call.Return()
	return _c
}

func (_c *FeatureResultInterface_HandleResult_Call) RunAndReturn(run func(api.ResultMessage)) *FeatureResultInterface_HandleResult_Call {
	_c.Call.Return(run)
	return _c
}

// NewFeatureResultInterface creates a new instance of FeatureResultInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFeatureResultInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *FeatureResultInterface {
	mock := &FeatureResultInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
