// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewFunctionDataInterface creates a new instance of FunctionDataInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFunctionDataInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *FunctionDataInterface {
	mock := &FunctionDataInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FunctionDataInterface is an autogenerated mock type for the FunctionDataInterface type
type FunctionDataInterface struct {
	mock.Mock
}

type FunctionDataInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *FunctionDataInterface) EXPECT() *FunctionDataInterface_Expecter {
	return &FunctionDataInterface_Expecter{mock: &_m.Mock}
}

// DataCopyAny provides a mock function for the type FunctionDataInterface
func (_mock *FunctionDataInterface) DataCopyAny() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DataCopyAny")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// FunctionDataInterface_DataCopyAny_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DataCopyAny'
type FunctionDataInterface_DataCopyAny_Call struct {
	*mock.Call
}

// DataCopyAny is a helper method to define mock.On call
func (_e *FunctionDataInterface_Expecter) DataCopyAny() *FunctionDataInterface_DataCopyAny_Call {
	return &FunctionDataInterface_DataCopyAny_Call{Call: _e.mock.On("DataCopyAny")}
}

func (_c *FunctionDataInterface_DataCopyAny_Call) Run(run func()) *FunctionDataInterface_DataCopyAny_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FunctionDataInterface_DataCopyAny_Call) Return(v any) *FunctionDataInterface_DataCopyAny_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *FunctionDataInterface_DataCopyAny_Call) RunAndReturn(run func() any) *FunctionDataInterface_DataCopyAny_Call {
	_c.Call.Return(run)
	return _c
}

// FunctionType provides a mock function for the type FunctionDataInterface
func (_mock *FunctionDataInterface) FunctionType() model.FunctionType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FunctionType")
	}

	var r0 model.FunctionType
	if returnFunc, ok := ret.Get(0).(func() model.FunctionType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(model.FunctionType)
	}
	return r0
}

// FunctionDataInterface_FunctionType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FunctionType'
type FunctionDataInterface_FunctionType_Call struct {
	*mock.Call
}

// FunctionType is a helper method to define mock.On call
func (_e *FunctionDataInterface_Expecter) FunctionType() *FunctionDataInterface_FunctionType_Call {
	return &FunctionDataInterface_FunctionType_Call{Call: _e.mock.On("FunctionType")}
}

func (_c *FunctionDataInterface_FunctionType_Call) Run(run func()) *FunctionDataInterface_FunctionType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FunctionDataInterface_FunctionType_Call) Return(functionType model.FunctionType) *FunctionDataInterface_FunctionType_Call {
	_c.Call.Return(functionType)
	return _c
}

func (_c *FunctionDataInterface_FunctionType_Call) RunAndReturn(run func() model.FunctionType) *FunctionDataInterface_FunctionType_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsPartialWrite provides a mock function for the type FunctionDataInterface
func (_mock *FunctionDataInterface) SupportsPartialWrite() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsPartialWrite")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// FunctionDataInterface_SupportsPartialWrite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsPartialWrite'
type FunctionDataInterface_SupportsPartialWrite_Call struct {
	*mock.Call
}

// SupportsPartialWrite is a helper method to define mock.On call
func (_e *FunctionDataInterface_Expecter) SupportsPartialWrite() *FunctionDataInterface_SupportsPartialWrite_Call {
	return &FunctionDataInterface_SupportsPartialWrite_Call{Call: _e.mock.On("SupportsPartialWrite")}
}

func (_c *FunctionDataInterface_SupportsPartialWrite_Call) Run(run func()) *FunctionDataInterface_SupportsPartialWrite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FunctionDataInterface_SupportsPartialWrite_Call) Return(b bool) *FunctionDataInterface_SupportsPartialWrite_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *FunctionDataInterface_SupportsPartialWrite_Call) RunAndReturn(run func() bool) *FunctionDataInterface_SupportsPartialWrite_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataAny provides a mock function for the type FunctionDataInterface
func (_mock *FunctionDataInterface) UpdateDataAny(remoteWrite bool, persist bool, data any, filterPartial *model.FilterType, filterDelete *model.FilterType, cmdFunction *model.FunctionType) (any, *model.ErrorType) {
	ret := _mock.Called(remoteWrite, persist, data, filterPartial, filterDelete, cmdFunction)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataAny")
	}

	var r0 any
	var r1 *model.ErrorType
	if returnFunc, ok := ret.Get(0).(func(bool, bool, any, *model.FilterType, *model.FilterType, *model.FunctionType) (any, *model.ErrorType)); ok {
		return returnFunc(remoteWrite, persist, data, filterPartial, filterDelete, cmdFunction)
	}
	if returnFunc, ok := ret.Get(0).(func(bool, bool, any, *model.FilterType, *model.FilterType, *model.FunctionType) any); ok {
		r0 = returnFunc(remoteWrite, persist, data, filterPartial, filterDelete, cmdFunction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(bool, bool, any, *model.FilterType, *model.FilterType, *model.FunctionType) *model.ErrorType); ok {
		r1 = returnFunc(remoteWrite, persist, data, filterPartial, filterDelete, cmdFunction)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.ErrorType)
		}
	}
	return r0, r1
}

// FunctionDataInterface_UpdateDataAny_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataAny'
type FunctionDataInterface_UpdateDataAny_Call struct {
	*mock.Call
}

// UpdateDataAny is a helper method to define mock.On call
//   - remoteWrite bool
//   - persist bool
//   - data any
//   - filterPartial *model.FilterType
//   - filterDelete *model.FilterType
//   - cmdFunction *model.FunctionType
func (_e *FunctionDataInterface_Expecter) UpdateDataAny(remoteWrite interface{}, persist interface{}, data interface{}, filterPartial interface{}, filterDelete interface{}, cmdFunction interface{}) *FunctionDataInterface_UpdateDataAny_Call {
	return &FunctionDataInterface_UpdateDataAny_Call{Call: _e.mock.On("UpdateDataAny", remoteWrite, persist, data, filterPartial, filterDelete, cmdFunction)}
}

func (_c *FunctionDataInterface_UpdateDataAny_Call) Run(run func(remoteWrite bool, persist bool, data any, filterPartial *model.FilterType, filterDelete *model.FilterType, cmdFunction *model.FunctionType)) *FunctionDataInterface_UpdateDataAny_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 *model.FilterType
		if args[3] != nil {
			arg3 = args[3].(*model.FilterType)
		}
		var arg4 *model.FilterType
		if args[4] != nil {
			arg4 = args[4].(*model.FilterType)
		}
		var arg5 *model.FunctionType
		if args[5] != nil {
			arg5 = args[5].(*model.FunctionType)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *FunctionDataInterface_UpdateDataAny_Call) Return(v any, errorType *model.ErrorType) *FunctionDataInterface_UpdateDataAny_Call {
	_c.Call.Return(v, errorType)
	return _c
}

func (_c *FunctionDataInterface_UpdateDataAny_Call) RunAndReturn(run func(remoteWrite bool, persist bool, data any, filterPartial *model.FilterType, filterDelete *model.FilterType, cmdFunction *model.FunctionType) (any, *model.ErrorType)) *FunctionDataInterface_UpdateDataAny_Call {
	_c.Call.Return(run)
	return _c
}
