// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewFunctionDataCmdInterface creates a new instance of FunctionDataCmdInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFunctionDataCmdInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *FunctionDataCmdInterface {
	mock := &FunctionDataCmdInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FunctionDataCmdInterface is an autogenerated mock type for the FunctionDataCmdInterface type
type FunctionDataCmdInterface struct {
	mock.Mock
}

type FunctionDataCmdInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *FunctionDataCmdInterface) EXPECT() *FunctionDataCmdInterface_Expecter {
	return &FunctionDataCmdInterface_Expecter{mock: &_m.Mock}
}

// DataCopyAny provides a mock function for the type FunctionDataCmdInterface
func (_mock *FunctionDataCmdInterface) DataCopyAny() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DataCopyAny")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// FunctionDataCmdInterface_DataCopyAny_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DataCopyAny'
type FunctionDataCmdInterface_DataCopyAny_Call struct {
	*mock.Call
}

// DataCopyAny is a helper method to define mock.On call
func (_e *FunctionDataCmdInterface_Expecter) DataCopyAny() *FunctionDataCmdInterface_DataCopyAny_Call {
	return &FunctionDataCmdInterface_DataCopyAny_Call{Call: _e.mock.On("DataCopyAny")}
}

func (_c *FunctionDataCmdInterface_DataCopyAny_Call) Run(run func()) *FunctionDataCmdInterface_DataCopyAny_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FunctionDataCmdInterface_DataCopyAny_Call) Return(v any) *FunctionDataCmdInterface_DataCopyAny_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *FunctionDataCmdInterface_DataCopyAny_Call) RunAndReturn(run func() any) *FunctionDataCmdInterface_DataCopyAny_Call {
	_c.Call.Return(run)
	return _c
}

// FunctionType provides a mock function for the type FunctionDataCmdInterface
func (_mock *FunctionDataCmdInterface) FunctionType() model.FunctionType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FunctionType")
	}

	var r0 model.FunctionType
	if returnFunc, ok := ret.Get(0).(func() model.FunctionType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(model.FunctionType)
	}
	return r0
}

// FunctionDataCmdInterface_FunctionType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FunctionType'
type FunctionDataCmdInterface_FunctionType_Call struct {
	*mock.Call
}

// FunctionType is a helper method to define mock.On call
func (_e *FunctionDataCmdInterface_Expecter) FunctionType() *FunctionDataCmdInterface_FunctionType_Call {
	return &FunctionDataCmdInterface_FunctionType_Call{Call: _e.mock.On("FunctionType")}
}

func (_c *FunctionDataCmdInterface_FunctionType_Call) Run(run func()) *FunctionDataCmdInterface_FunctionType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FunctionDataCmdInterface_FunctionType_Call) Return(functionType model.FunctionType) *FunctionDataCmdInterface_FunctionType_Call {
	_c.Call.Return(functionType)
	return _c
}

func (_c *FunctionDataCmdInterface_FunctionType_Call) RunAndReturn(run func() model.FunctionType) *FunctionDataCmdInterface_FunctionType_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyOrWriteCmdType provides a mock function for the type FunctionDataCmdInterface
func (_mock *FunctionDataCmdInterface) NotifyOrWriteCmdType(deleteSelector any, partialSelector any, partialWithoutSelector bool, deleteElements any) model.CmdType {
	ret := _mock.Called(deleteSelector, partialSelector, partialWithoutSelector, deleteElements)

	if len(ret) == 0 {
		panic("no return value specified for NotifyOrWriteCmdType")
	}

	var r0 model.CmdType
	if returnFunc, ok := ret.Get(0).(func(any, any, bool, any) model.CmdType); ok {
		r0 = returnFunc(deleteSelector, partialSelector, partialWithoutSelector, deleteElements)
	} else {
		r0 = ret.Get(0).(model.CmdType)
	}
	return r0
}

// FunctionDataCmdInterface_NotifyOrWriteCmdType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyOrWriteCmdType'
type FunctionDataCmdInterface_NotifyOrWriteCmdType_Call struct {
	*mock.Call
}

// NotifyOrWriteCmdType is a helper method to define mock.On call
//   - deleteSelector any
//   - partialSelector any
//   - partialWithoutSelector bool
//   - deleteElements any
func (_e *FunctionDataCmdInterface_Expecter) NotifyOrWriteCmdType(deleteSelector interface{}, partialSelector interface{}, partialWithoutSelector interface{}, deleteElements interface{}) *FunctionDataCmdInterface_NotifyOrWriteCmdType_Call {
	return &FunctionDataCmdInterface_NotifyOrWriteCmdType_Call{Call: _e.mock.On("NotifyOrWriteCmdType", deleteSelector, partialSelector, partialWithoutSelector, deleteElements)}
}

func (_c *FunctionDataCmdInterface_NotifyOrWriteCmdType_Call) Run(run func(deleteSelector any, partialSelector any, partialWithoutSelector bool, deleteElements any)) *FunctionDataCmdInterface_NotifyOrWriteCmdType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *FunctionDataCmdInterface_NotifyOrWriteCmdType_Call) Return(cmdType model.CmdType) *FunctionDataCmdInterface_NotifyOrWriteCmdType_Call {
	_c.Call.Return(cmdType)
	return _c
}

func (_c *FunctionDataCmdInterface_NotifyOrWriteCmdType_Call) RunAndReturn(run func(deleteSelector any, partialSelector any, partialWithoutSelector bool, deleteElements any) model.CmdType) *FunctionDataCmdInterface_NotifyOrWriteCmdType_Call {
	_c.Call.Return(run)
	return _c
}

// ReadCmdType provides a mock function for the type FunctionDataCmdInterface
func (_mock *FunctionDataCmdInterface) ReadCmdType(partialSelector any, elements any) model.CmdType {
	ret := _mock.Called(partialSelector, elements)

	if len(ret) == 0 {
		panic("no return value specified for ReadCmdType")
	}

	var r0 model.CmdType
	if returnFunc, ok := ret.Get(0).(func(any, any) model.CmdType); ok {
		r0 = returnFunc(partialSelector, elements)
	} else {
		r0 = ret.Get(0).(model.CmdType)
	}
	return r0
}

// FunctionDataCmdInterface_ReadCmdType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadCmdType'
type FunctionDataCmdInterface_ReadCmdType_Call struct {
	*mock.Call
}

// ReadCmdType is a helper method to define mock.On call
//   - partialSelector any
//   - elements any
func (_e *FunctionDataCmdInterface_Expecter) ReadCmdType(partialSelector interface{}, elements interface{}) *FunctionDataCmdInterface_ReadCmdType_Call {
	return &FunctionDataCmdInterface_ReadCmdType_Call{Call: _e.mock.On("ReadCmdType", partialSelector, elements)}
}

func (_c *FunctionDataCmdInterface_ReadCmdType_Call) Run(run func(partialSelector any, elements any)) *FunctionDataCmdInterface_ReadCmdType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FunctionDataCmdInterface_ReadCmdType_Call) Return(cmdType model.CmdType) *FunctionDataCmdInterface_ReadCmdType_Call {
	_c.Call.Return(cmdType)
	return _c
}

func (_c *FunctionDataCmdInterface_ReadCmdType_Call) RunAndReturn(run func(partialSelector any, elements any) model.CmdType) *FunctionDataCmdInterface_ReadCmdType_Call {
	_c.Call.Return(run)
	return _c
}

// ReplyCmdType provides a mock function for the type FunctionDataCmdInterface
func (_mock *FunctionDataCmdInterface) ReplyCmdType(partial bool) model.CmdType {
	ret := _mock.Called(partial)

	if len(ret) == 0 {
		panic("no return value specified for ReplyCmdType")
	}

	var r0 model.CmdType
	if returnFunc, ok := ret.Get(0).(func(bool) model.CmdType); ok {
		r0 = returnFunc(partial)
	} else {
		r0 = ret.Get(0).(model.CmdType)
	}
	return r0
}

// FunctionDataCmdInterface_ReplyCmdType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplyCmdType'
type FunctionDataCmdInterface_ReplyCmdType_Call struct {
	*mock.Call
}

// ReplyCmdType is a helper method to define mock.On call
//   - partial bool
func (_e *FunctionDataCmdInterface_Expecter) ReplyCmdType(partial interface{}) *FunctionDataCmdInterface_ReplyCmdType_Call {
	return &FunctionDataCmdInterface_ReplyCmdType_Call{Call: _e.mock.On("ReplyCmdType", partial)}
}

func (_c *FunctionDataCmdInterface_ReplyCmdType_Call) Run(run func(partial bool)) *FunctionDataCmdInterface_ReplyCmdType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FunctionDataCmdInterface_ReplyCmdType_Call) Return(cmdType model.CmdType) *FunctionDataCmdInterface_ReplyCmdType_Call {
	_c.Call.Return(cmdType)
	return _c
}

func (_c *FunctionDataCmdInterface_ReplyCmdType_Call) RunAndReturn(run func(partial bool) model.CmdType) *FunctionDataCmdInterface_ReplyCmdType_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsPartialWrite provides a mock function for the type FunctionDataCmdInterface
func (_mock *FunctionDataCmdInterface) SupportsPartialWrite() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsPartialWrite")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// FunctionDataCmdInterface_SupportsPartialWrite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsPartialWrite'
type FunctionDataCmdInterface_SupportsPartialWrite_Call struct {
	*mock.Call
}

// SupportsPartialWrite is a helper method to define mock.On call
func (_e *FunctionDataCmdInterface_Expecter) SupportsPartialWrite() *FunctionDataCmdInterface_SupportsPartialWrite_Call {
	return &FunctionDataCmdInterface_SupportsPartialWrite_Call{Call: _e.mock.On("SupportsPartialWrite")}
}

func (_c *FunctionDataCmdInterface_SupportsPartialWrite_Call) Run(run func()) *FunctionDataCmdInterface_SupportsPartialWrite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FunctionDataCmdInterface_SupportsPartialWrite_Call) Return(b bool) *FunctionDataCmdInterface_SupportsPartialWrite_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *FunctionDataCmdInterface_SupportsPartialWrite_Call) RunAndReturn(run func() bool) *FunctionDataCmdInterface_SupportsPartialWrite_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataAny provides a mock function for the type FunctionDataCmdInterface
func (_mock *FunctionDataCmdInterface) UpdateDataAny(remoteWrite bool, persist bool, data any, filterPartial *model.FilterType, filterDelete *model.FilterType) (any, *model.ErrorType) {
	ret := _mock.Called(remoteWrite, persist, data, filterPartial, filterDelete)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataAny")
	}

	var r0 any
	var r1 *model.ErrorType
	if returnFunc, ok := ret.Get(0).(func(bool, bool, any, *model.FilterType, *model.FilterType) (any, *model.ErrorType)); ok {
		return returnFunc(remoteWrite, persist, data, filterPartial, filterDelete)
	}
	if returnFunc, ok := ret.Get(0).(func(bool, bool, any, *model.FilterType, *model.FilterType) any); ok {
		r0 = returnFunc(remoteWrite, persist, data, filterPartial, filterDelete)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(bool, bool, any, *model.FilterType, *model.FilterType) *model.ErrorType); ok {
		r1 = returnFunc(remoteWrite, persist, data, filterPartial, filterDelete)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.ErrorType)
		}
	}
	return r0, r1
}

// FunctionDataCmdInterface_UpdateDataAny_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataAny'
type FunctionDataCmdInterface_UpdateDataAny_Call struct {
	*mock.Call
}

// UpdateDataAny is a helper method to define mock.On call
//   - remoteWrite bool
//   - persist bool
//   - data any
//   - filterPartial *model.FilterType
//   - filterDelete *model.FilterType
func (_e *FunctionDataCmdInterface_Expecter) UpdateDataAny(remoteWrite interface{}, persist interface{}, data interface{}, filterPartial interface{}, filterDelete interface{}) *FunctionDataCmdInterface_UpdateDataAny_Call {
	return &FunctionDataCmdInterface_UpdateDataAny_Call{Call: _e.mock.On("UpdateDataAny", remoteWrite, persist, data, filterPartial, filterDelete)}
}

func (_c *FunctionDataCmdInterface_UpdateDataAny_Call) Run(run func(remoteWrite bool, persist bool, data any, filterPartial *model.FilterType, filterDelete *model.FilterType)) *FunctionDataCmdInterface_UpdateDataAny_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 *model.FilterType
		if args[3] != nil {
			arg3 = args[3].(*model.FilterType)
		}
		var arg4 *model.FilterType
		if args[4] != nil {
			arg4 = args[4].(*model.FilterType)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *FunctionDataCmdInterface_UpdateDataAny_Call) Return(v any, errorType *model.ErrorType) *FunctionDataCmdInterface_UpdateDataAny_Call {
	_c.Call.Return(v, errorType)
	return _c
}

func (_c *FunctionDataCmdInterface_UpdateDataAny_Call) RunAndReturn(run func(remoteWrite bool, persist bool, data any, filterPartial *model.FilterType, filterDelete *model.FilterType) (any, *model.ErrorType)) *FunctionDataCmdInterface_UpdateDataAny_Call {
	_c.Call.Return(run)
	return _c
}
