// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	api "github.com/enbility/spine-go/api"
	mock "github.com/stretchr/testify/mock"
)

// HeartbeatManager is an autogenerated mock type for the HeartbeatManager type
type HeartbeatManager struct {
	mock.Mock
}

type HeartbeatManager_Expecter struct {
	mock *mock.Mock
}

func (_m *HeartbeatManager) EXPECT() *HeartbeatManager_Expecter {
	return &HeartbeatManager_Expecter{mock: &_m.Mock}
}

// IsHeartbeatRunning provides a mock function with given fields:
func (_m *HeartbeatManager) IsHeartbeatRunning() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsHeartbeatRunning")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// HeartbeatManager_IsHeartbeatRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsHeartbeatRunning'
type HeartbeatManager_IsHeartbeatRunning_Call struct {
	*mock.Call
}

// IsHeartbeatRunning is a helper method to define mock.On call
func (_e *HeartbeatManager_Expecter) IsHeartbeatRunning() *HeartbeatManager_IsHeartbeatRunning_Call {
	return &HeartbeatManager_IsHeartbeatRunning_Call{Call: _e.mock.On("IsHeartbeatRunning")}
}

func (_c *HeartbeatManager_IsHeartbeatRunning_Call) Run(run func()) *HeartbeatManager_IsHeartbeatRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HeartbeatManager_IsHeartbeatRunning_Call) Return(_a0 bool) *HeartbeatManager_IsHeartbeatRunning_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HeartbeatManager_IsHeartbeatRunning_Call) RunAndReturn(run func() bool) *HeartbeatManager_IsHeartbeatRunning_Call {
	_c.Call.Return(run)
	return _c
}

// SetLocalFeature provides a mock function with given fields: entity, feature
func (_m *HeartbeatManager) SetLocalFeature(entity api.EntityLocal, feature api.FeatureLocal) {
	_m.Called(entity, feature)
}

// HeartbeatManager_SetLocalFeature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLocalFeature'
type HeartbeatManager_SetLocalFeature_Call struct {
	*mock.Call
}

// SetLocalFeature is a helper method to define mock.On call
//   - entity api.EntityLocal
//   - feature api.FeatureLocal
func (_e *HeartbeatManager_Expecter) SetLocalFeature(entity interface{}, feature interface{}) *HeartbeatManager_SetLocalFeature_Call {
	return &HeartbeatManager_SetLocalFeature_Call{Call: _e.mock.On("SetLocalFeature", entity, feature)}
}

func (_c *HeartbeatManager_SetLocalFeature_Call) Run(run func(entity api.EntityLocal, feature api.FeatureLocal)) *HeartbeatManager_SetLocalFeature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EntityLocal), args[1].(api.FeatureLocal))
	})
	return _c
}

func (_c *HeartbeatManager_SetLocalFeature_Call) Return() *HeartbeatManager_SetLocalFeature_Call {
	_c.Call.Return()
	return _c
}

func (_c *HeartbeatManager_SetLocalFeature_Call) RunAndReturn(run func(api.EntityLocal, api.FeatureLocal)) *HeartbeatManager_SetLocalFeature_Call {
	_c.Call.Return(run)
	return _c
}

// StartHeartbeat provides a mock function with given fields:
func (_m *HeartbeatManager) StartHeartbeat() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartHeartbeat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HeartbeatManager_StartHeartbeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartHeartbeat'
type HeartbeatManager_StartHeartbeat_Call struct {
	*mock.Call
}

// StartHeartbeat is a helper method to define mock.On call
func (_e *HeartbeatManager_Expecter) StartHeartbeat() *HeartbeatManager_StartHeartbeat_Call {
	return &HeartbeatManager_StartHeartbeat_Call{Call: _e.mock.On("StartHeartbeat")}
}

func (_c *HeartbeatManager_StartHeartbeat_Call) Run(run func()) *HeartbeatManager_StartHeartbeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HeartbeatManager_StartHeartbeat_Call) Return(_a0 error) *HeartbeatManager_StartHeartbeat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HeartbeatManager_StartHeartbeat_Call) RunAndReturn(run func() error) *HeartbeatManager_StartHeartbeat_Call {
	_c.Call.Return(run)
	return _c
}

// StopHeartbeat provides a mock function with given fields:
func (_m *HeartbeatManager) StopHeartbeat() {
	_m.Called()
}

// HeartbeatManager_StopHeartbeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopHeartbeat'
type HeartbeatManager_StopHeartbeat_Call struct {
	*mock.Call
}

// StopHeartbeat is a helper method to define mock.On call
func (_e *HeartbeatManager_Expecter) StopHeartbeat() *HeartbeatManager_StopHeartbeat_Call {
	return &HeartbeatManager_StopHeartbeat_Call{Call: _e.mock.On("StopHeartbeat")}
}

func (_c *HeartbeatManager_StopHeartbeat_Call) Run(run func()) *HeartbeatManager_StopHeartbeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HeartbeatManager_StopHeartbeat_Call) Return() *HeartbeatManager_StopHeartbeat_Call {
	_c.Call.Return()
	return _c
}

func (_c *HeartbeatManager_StopHeartbeat_Call) RunAndReturn(run func()) *HeartbeatManager_StopHeartbeat_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateHeartbeatOnSubscriptions provides a mock function with given fields:
func (_m *HeartbeatManager) UpdateHeartbeatOnSubscriptions() {
	_m.Called()
}

// HeartbeatManager_UpdateHeartbeatOnSubscriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateHeartbeatOnSubscriptions'
type HeartbeatManager_UpdateHeartbeatOnSubscriptions_Call struct {
	*mock.Call
}

// UpdateHeartbeatOnSubscriptions is a helper method to define mock.On call
func (_e *HeartbeatManager_Expecter) UpdateHeartbeatOnSubscriptions() *HeartbeatManager_UpdateHeartbeatOnSubscriptions_Call {
	return &HeartbeatManager_UpdateHeartbeatOnSubscriptions_Call{Call: _e.mock.On("UpdateHeartbeatOnSubscriptions")}
}

func (_c *HeartbeatManager_UpdateHeartbeatOnSubscriptions_Call) Run(run func()) *HeartbeatManager_UpdateHeartbeatOnSubscriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HeartbeatManager_UpdateHeartbeatOnSubscriptions_Call) Return() *HeartbeatManager_UpdateHeartbeatOnSubscriptions_Call {
	_c.Call.Return()
	return _c
}

func (_c *HeartbeatManager_UpdateHeartbeatOnSubscriptions_Call) RunAndReturn(run func()) *HeartbeatManager_UpdateHeartbeatOnSubscriptions_Call {
	_c.Call.Return(run)
	return _c
}

// NewHeartbeatManager creates a new instance of HeartbeatManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHeartbeatManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *HeartbeatManager {
	mock := &HeartbeatManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
