// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	api "github.com/enbility/spine-go/api"
	mock "github.com/stretchr/testify/mock"

	model "github.com/enbility/spine-go/model"

	time "time"
)

// NodeManagement is an autogenerated mock type for the NodeManagement type
type NodeManagement struct {
	mock.Mock
}

type NodeManagement_Expecter struct {
	mock *mock.Mock
}

func (_m *NodeManagement) EXPECT() *NodeManagement_Expecter {
	return &NodeManagement_Expecter{mock: &_m.Mock}
}

// AddFunctionType provides a mock function with given fields: function, read, write
func (_m *NodeManagement) AddFunctionType(function model.FunctionType, read bool, write bool) {
	_m.Called(function, read, write)
}

// NodeManagement_AddFunctionType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFunctionType'
type NodeManagement_AddFunctionType_Call struct {
	*mock.Call
}

// AddFunctionType is a helper method to define mock.On call
//   - function model.FunctionType
//   - read bool
//   - write bool
func (_e *NodeManagement_Expecter) AddFunctionType(function interface{}, read interface{}, write interface{}) *NodeManagement_AddFunctionType_Call {
	return &NodeManagement_AddFunctionType_Call{Call: _e.mock.On("AddFunctionType", function, read, write)}
}

func (_c *NodeManagement_AddFunctionType_Call) Run(run func(function model.FunctionType, read bool, write bool)) *NodeManagement_AddFunctionType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.FunctionType), args[1].(bool), args[2].(bool))
	})
	return _c
}

func (_c *NodeManagement_AddFunctionType_Call) Return() *NodeManagement_AddFunctionType_Call {
	_c.Call.Return()
	return _c
}

func (_c *NodeManagement_AddFunctionType_Call) RunAndReturn(run func(model.FunctionType, bool, bool)) *NodeManagement_AddFunctionType_Call {
	_c.Call.Return(run)
	return _c
}

// AddResultCallback provides a mock function with given fields: msgCounterReference, function
func (_m *NodeManagement) AddResultCallback(msgCounterReference model.MsgCounterType, function func(api.ResultMessage)) {
	_m.Called(msgCounterReference, function)
}

// NodeManagement_AddResultCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddResultCallback'
type NodeManagement_AddResultCallback_Call struct {
	*mock.Call
}

// AddResultCallback is a helper method to define mock.On call
//   - msgCounterReference model.MsgCounterType
//   - function func(api.ResultMessage)
func (_e *NodeManagement_Expecter) AddResultCallback(msgCounterReference interface{}, function interface{}) *NodeManagement_AddResultCallback_Call {
	return &NodeManagement_AddResultCallback_Call{Call: _e.mock.On("AddResultCallback", msgCounterReference, function)}
}

func (_c *NodeManagement_AddResultCallback_Call) Run(run func(msgCounterReference model.MsgCounterType, function func(api.ResultMessage))) *NodeManagement_AddResultCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.MsgCounterType), args[1].(func(api.ResultMessage)))
	})
	return _c
}

func (_c *NodeManagement_AddResultCallback_Call) Return() *NodeManagement_AddResultCallback_Call {
	_c.Call.Return()
	return _c
}

func (_c *NodeManagement_AddResultCallback_Call) RunAndReturn(run func(model.MsgCounterType, func(api.ResultMessage))) *NodeManagement_AddResultCallback_Call {
	_c.Call.Return(run)
	return _c
}

// AddResultHandler provides a mock function with given fields: handler
func (_m *NodeManagement) AddResultHandler(handler api.FeatureResult) {
	_m.Called(handler)
}

// NodeManagement_AddResultHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddResultHandler'
type NodeManagement_AddResultHandler_Call struct {
	*mock.Call
}

// AddResultHandler is a helper method to define mock.On call
//   - handler api.FeatureResult
func (_e *NodeManagement_Expecter) AddResultHandler(handler interface{}) *NodeManagement_AddResultHandler_Call {
	return &NodeManagement_AddResultHandler_Call{Call: _e.mock.On("AddResultHandler", handler)}
}

func (_c *NodeManagement_AddResultHandler_Call) Run(run func(handler api.FeatureResult)) *NodeManagement_AddResultHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.FeatureResult))
	})
	return _c
}

func (_c *NodeManagement_AddResultHandler_Call) Return() *NodeManagement_AddResultHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *NodeManagement_AddResultHandler_Call) RunAndReturn(run func(api.FeatureResult)) *NodeManagement_AddResultHandler_Call {
	_c.Call.Return(run)
	return _c
}

// Address provides a mock function with given fields:
func (_m *NodeManagement) Address() *model.FeatureAddressType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 *model.FeatureAddressType
	if rf, ok := ret.Get(0).(func() *model.FeatureAddressType); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.FeatureAddressType)
		}
	}

	return r0
}

// NodeManagement_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type NodeManagement_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *NodeManagement_Expecter) Address() *NodeManagement_Address_Call {
	return &NodeManagement_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *NodeManagement_Address_Call) Run(run func()) *NodeManagement_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NodeManagement_Address_Call) Return(_a0 *model.FeatureAddressType) *NodeManagement_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NodeManagement_Address_Call) RunAndReturn(run func() *model.FeatureAddressType) *NodeManagement_Address_Call {
	_c.Call.Return(run)
	return _c
}

// Bind provides a mock function with given fields: remoteAdress
func (_m *NodeManagement) Bind(remoteAdress *model.FeatureAddressType) (*model.MsgCounterType, *model.ErrorType) {
	ret := _m.Called(remoteAdress)

	if len(ret) == 0 {
		panic("no return value specified for Bind")
	}

	var r0 *model.MsgCounterType
	var r1 *model.ErrorType
	if rf, ok := ret.Get(0).(func(*model.FeatureAddressType) (*model.MsgCounterType, *model.ErrorType)); ok {
		return rf(remoteAdress)
	}
	if rf, ok := ret.Get(0).(func(*model.FeatureAddressType) *model.MsgCounterType); ok {
		r0 = rf(remoteAdress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.FeatureAddressType) *model.ErrorType); ok {
		r1 = rf(remoteAdress)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.ErrorType)
		}
	}

	return r0, r1
}

// NodeManagement_Bind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bind'
type NodeManagement_Bind_Call struct {
	*mock.Call
}

// Bind is a helper method to define mock.On call
//   - remoteAdress *model.FeatureAddressType
func (_e *NodeManagement_Expecter) Bind(remoteAdress interface{}) *NodeManagement_Bind_Call {
	return &NodeManagement_Bind_Call{Call: _e.mock.On("Bind", remoteAdress)}
}

func (_c *NodeManagement_Bind_Call) Run(run func(remoteAdress *model.FeatureAddressType)) *NodeManagement_Bind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.FeatureAddressType))
	})
	return _c
}

func (_c *NodeManagement_Bind_Call) Return(_a0 *model.MsgCounterType, _a1 *model.ErrorType) *NodeManagement_Bind_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NodeManagement_Bind_Call) RunAndReturn(run func(*model.FeatureAddressType) (*model.MsgCounterType, *model.ErrorType)) *NodeManagement_Bind_Call {
	_c.Call.Return(run)
	return _c
}

// DataCopy provides a mock function with given fields: function
func (_m *NodeManagement) DataCopy(function model.FunctionType) interface{} {
	ret := _m.Called(function)

	if len(ret) == 0 {
		panic("no return value specified for DataCopy")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(model.FunctionType) interface{}); ok {
		r0 = rf(function)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// NodeManagement_DataCopy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DataCopy'
type NodeManagement_DataCopy_Call struct {
	*mock.Call
}

// DataCopy is a helper method to define mock.On call
//   - function model.FunctionType
func (_e *NodeManagement_Expecter) DataCopy(function interface{}) *NodeManagement_DataCopy_Call {
	return &NodeManagement_DataCopy_Call{Call: _e.mock.On("DataCopy", function)}
}

func (_c *NodeManagement_DataCopy_Call) Run(run func(function model.FunctionType)) *NodeManagement_DataCopy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.FunctionType))
	})
	return _c
}

func (_c *NodeManagement_DataCopy_Call) Return(_a0 interface{}) *NodeManagement_DataCopy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NodeManagement_DataCopy_Call) RunAndReturn(run func(model.FunctionType) interface{}) *NodeManagement_DataCopy_Call {
	_c.Call.Return(run)
	return _c
}

// Description provides a mock function with given fields:
func (_m *NodeManagement) Description() *model.DescriptionType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Description")
	}

	var r0 *model.DescriptionType
	if rf, ok := ret.Get(0).(func() *model.DescriptionType); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DescriptionType)
		}
	}

	return r0
}

// NodeManagement_Description_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Description'
type NodeManagement_Description_Call struct {
	*mock.Call
}

// Description is a helper method to define mock.On call
func (_e *NodeManagement_Expecter) Description() *NodeManagement_Description_Call {
	return &NodeManagement_Description_Call{Call: _e.mock.On("Description")}
}

func (_c *NodeManagement_Description_Call) Run(run func()) *NodeManagement_Description_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NodeManagement_Description_Call) Return(_a0 *model.DescriptionType) *NodeManagement_Description_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NodeManagement_Description_Call) RunAndReturn(run func() *model.DescriptionType) *NodeManagement_Description_Call {
	_c.Call.Return(run)
	return _c
}

// Device provides a mock function with given fields:
func (_m *NodeManagement) Device() api.DeviceLocal {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Device")
	}

	var r0 api.DeviceLocal
	if rf, ok := ret.Get(0).(func() api.DeviceLocal); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.DeviceLocal)
		}
	}

	return r0
}

// NodeManagement_Device_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Device'
type NodeManagement_Device_Call struct {
	*mock.Call
}

// Device is a helper method to define mock.On call
func (_e *NodeManagement_Expecter) Device() *NodeManagement_Device_Call {
	return &NodeManagement_Device_Call{Call: _e.mock.On("Device")}
}

func (_c *NodeManagement_Device_Call) Run(run func()) *NodeManagement_Device_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NodeManagement_Device_Call) Return(_a0 api.DeviceLocal) *NodeManagement_Device_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NodeManagement_Device_Call) RunAndReturn(run func() api.DeviceLocal) *NodeManagement_Device_Call {
	_c.Call.Return(run)
	return _c
}

// Entity provides a mock function with given fields:
func (_m *NodeManagement) Entity() api.EntityLocal {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Entity")
	}

	var r0 api.EntityLocal
	if rf, ok := ret.Get(0).(func() api.EntityLocal); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.EntityLocal)
		}
	}

	return r0
}

// NodeManagement_Entity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Entity'
type NodeManagement_Entity_Call struct {
	*mock.Call
}

// Entity is a helper method to define mock.On call
func (_e *NodeManagement_Expecter) Entity() *NodeManagement_Entity_Call {
	return &NodeManagement_Entity_Call{Call: _e.mock.On("Entity")}
}

func (_c *NodeManagement_Entity_Call) Run(run func()) *NodeManagement_Entity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NodeManagement_Entity_Call) Return(_a0 api.EntityLocal) *NodeManagement_Entity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NodeManagement_Entity_Call) RunAndReturn(run func() api.EntityLocal) *NodeManagement_Entity_Call {
	_c.Call.Return(run)
	return _c
}

// FetchRequestData provides a mock function with given fields: msgCounter, destination
func (_m *NodeManagement) FetchRequestData(msgCounter model.MsgCounterType, destination api.FeatureRemote) (interface{}, *model.ErrorType) {
	ret := _m.Called(msgCounter, destination)

	if len(ret) == 0 {
		panic("no return value specified for FetchRequestData")
	}

	var r0 interface{}
	var r1 *model.ErrorType
	if rf, ok := ret.Get(0).(func(model.MsgCounterType, api.FeatureRemote) (interface{}, *model.ErrorType)); ok {
		return rf(msgCounter, destination)
	}
	if rf, ok := ret.Get(0).(func(model.MsgCounterType, api.FeatureRemote) interface{}); ok {
		r0 = rf(msgCounter, destination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(model.MsgCounterType, api.FeatureRemote) *model.ErrorType); ok {
		r1 = rf(msgCounter, destination)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.ErrorType)
		}
	}

	return r0, r1
}

// NodeManagement_FetchRequestData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchRequestData'
type NodeManagement_FetchRequestData_Call struct {
	*mock.Call
}

// FetchRequestData is a helper method to define mock.On call
//   - msgCounter model.MsgCounterType
//   - destination api.FeatureRemote
func (_e *NodeManagement_Expecter) FetchRequestData(msgCounter interface{}, destination interface{}) *NodeManagement_FetchRequestData_Call {
	return &NodeManagement_FetchRequestData_Call{Call: _e.mock.On("FetchRequestData", msgCounter, destination)}
}

func (_c *NodeManagement_FetchRequestData_Call) Run(run func(msgCounter model.MsgCounterType, destination api.FeatureRemote)) *NodeManagement_FetchRequestData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.MsgCounterType), args[1].(api.FeatureRemote))
	})
	return _c
}

func (_c *NodeManagement_FetchRequestData_Call) Return(_a0 interface{}, _a1 *model.ErrorType) *NodeManagement_FetchRequestData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NodeManagement_FetchRequestData_Call) RunAndReturn(run func(model.MsgCounterType, api.FeatureRemote) (interface{}, *model.ErrorType)) *NodeManagement_FetchRequestData_Call {
	_c.Call.Return(run)
	return _c
}

// HandleMessage provides a mock function with given fields: message
func (_m *NodeManagement) HandleMessage(message *api.Message) *model.ErrorType {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for HandleMessage")
	}

	var r0 *model.ErrorType
	if rf, ok := ret.Get(0).(func(*api.Message) *model.ErrorType); ok {
		r0 = rf(message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ErrorType)
		}
	}

	return r0
}

// NodeManagement_HandleMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleMessage'
type NodeManagement_HandleMessage_Call struct {
	*mock.Call
}

// HandleMessage is a helper method to define mock.On call
//   - message *api.Message
func (_e *NodeManagement_Expecter) HandleMessage(message interface{}) *NodeManagement_HandleMessage_Call {
	return &NodeManagement_HandleMessage_Call{Call: _e.mock.On("HandleMessage", message)}
}

func (_c *NodeManagement_HandleMessage_Call) Run(run func(message *api.Message)) *NodeManagement_HandleMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*api.Message))
	})
	return _c
}

func (_c *NodeManagement_HandleMessage_Call) Return(_a0 *model.ErrorType) *NodeManagement_HandleMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NodeManagement_HandleMessage_Call) RunAndReturn(run func(*api.Message) *model.ErrorType) *NodeManagement_HandleMessage_Call {
	_c.Call.Return(run)
	return _c
}

// Information provides a mock function with given fields:
func (_m *NodeManagement) Information() *model.NodeManagementDetailedDiscoveryFeatureInformationType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Information")
	}

	var r0 *model.NodeManagementDetailedDiscoveryFeatureInformationType
	if rf, ok := ret.Get(0).(func() *model.NodeManagementDetailedDiscoveryFeatureInformationType); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.NodeManagementDetailedDiscoveryFeatureInformationType)
		}
	}

	return r0
}

// NodeManagement_Information_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Information'
type NodeManagement_Information_Call struct {
	*mock.Call
}

// Information is a helper method to define mock.On call
func (_e *NodeManagement_Expecter) Information() *NodeManagement_Information_Call {
	return &NodeManagement_Information_Call{Call: _e.mock.On("Information")}
}

func (_c *NodeManagement_Information_Call) Run(run func()) *NodeManagement_Information_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NodeManagement_Information_Call) Return(_a0 *model.NodeManagementDetailedDiscoveryFeatureInformationType) *NodeManagement_Information_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NodeManagement_Information_Call) RunAndReturn(run func() *model.NodeManagementDetailedDiscoveryFeatureInformationType) *NodeManagement_Information_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyData provides a mock function with given fields: function, deleteSelector, partialSelector, partialWithoutSelector, deleteElements, destination
func (_m *NodeManagement) NotifyData(function model.FunctionType, deleteSelector interface{}, partialSelector interface{}, partialWithoutSelector bool, deleteElements interface{}, destination api.FeatureRemote) (*model.MsgCounterType, *model.ErrorType) {
	ret := _m.Called(function, deleteSelector, partialSelector, partialWithoutSelector, deleteElements, destination)

	if len(ret) == 0 {
		panic("no return value specified for NotifyData")
	}

	var r0 *model.MsgCounterType
	var r1 *model.ErrorType
	if rf, ok := ret.Get(0).(func(model.FunctionType, interface{}, interface{}, bool, interface{}, api.FeatureRemote) (*model.MsgCounterType, *model.ErrorType)); ok {
		return rf(function, deleteSelector, partialSelector, partialWithoutSelector, deleteElements, destination)
	}
	if rf, ok := ret.Get(0).(func(model.FunctionType, interface{}, interface{}, bool, interface{}, api.FeatureRemote) *model.MsgCounterType); ok {
		r0 = rf(function, deleteSelector, partialSelector, partialWithoutSelector, deleteElements, destination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}

	if rf, ok := ret.Get(1).(func(model.FunctionType, interface{}, interface{}, bool, interface{}, api.FeatureRemote) *model.ErrorType); ok {
		r1 = rf(function, deleteSelector, partialSelector, partialWithoutSelector, deleteElements, destination)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.ErrorType)
		}
	}

	return r0, r1
}

// NodeManagement_NotifyData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyData'
type NodeManagement_NotifyData_Call struct {
	*mock.Call
}

// NotifyData is a helper method to define mock.On call
//   - function model.FunctionType
//   - deleteSelector interface{}
//   - partialSelector interface{}
//   - partialWithoutSelector bool
//   - deleteElements interface{}
//   - destination api.FeatureRemote
func (_e *NodeManagement_Expecter) NotifyData(function interface{}, deleteSelector interface{}, partialSelector interface{}, partialWithoutSelector interface{}, deleteElements interface{}, destination interface{}) *NodeManagement_NotifyData_Call {
	return &NodeManagement_NotifyData_Call{Call: _e.mock.On("NotifyData", function, deleteSelector, partialSelector, partialWithoutSelector, deleteElements, destination)}
}

func (_c *NodeManagement_NotifyData_Call) Run(run func(function model.FunctionType, deleteSelector interface{}, partialSelector interface{}, partialWithoutSelector bool, deleteElements interface{}, destination api.FeatureRemote)) *NodeManagement_NotifyData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.FunctionType), args[1].(interface{}), args[2].(interface{}), args[3].(bool), args[4].(interface{}), args[5].(api.FeatureRemote))
	})
	return _c
}

func (_c *NodeManagement_NotifyData_Call) Return(_a0 *model.MsgCounterType, _a1 *model.ErrorType) *NodeManagement_NotifyData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NodeManagement_NotifyData_Call) RunAndReturn(run func(model.FunctionType, interface{}, interface{}, bool, interface{}, api.FeatureRemote) (*model.MsgCounterType, *model.ErrorType)) *NodeManagement_NotifyData_Call {
	_c.Call.Return(run)
	return _c
}

// Operations provides a mock function with given fields:
func (_m *NodeManagement) Operations() map[model.FunctionType]api.Operations {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Operations")
	}

	var r0 map[model.FunctionType]api.Operations
	if rf, ok := ret.Get(0).(func() map[model.FunctionType]api.Operations); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[model.FunctionType]api.Operations)
		}
	}

	return r0
}

// NodeManagement_Operations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Operations'
type NodeManagement_Operations_Call struct {
	*mock.Call
}

// Operations is a helper method to define mock.On call
func (_e *NodeManagement_Expecter) Operations() *NodeManagement_Operations_Call {
	return &NodeManagement_Operations_Call{Call: _e.mock.On("Operations")}
}

func (_c *NodeManagement_Operations_Call) Run(run func()) *NodeManagement_Operations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NodeManagement_Operations_Call) Return(_a0 map[model.FunctionType]api.Operations) *NodeManagement_Operations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NodeManagement_Operations_Call) RunAndReturn(run func() map[model.FunctionType]api.Operations) *NodeManagement_Operations_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAllBindings provides a mock function with given fields:
func (_m *NodeManagement) RemoveAllBindings() {
	_m.Called()
}

// NodeManagement_RemoveAllBindings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAllBindings'
type NodeManagement_RemoveAllBindings_Call struct {
	*mock.Call
}

// RemoveAllBindings is a helper method to define mock.On call
func (_e *NodeManagement_Expecter) RemoveAllBindings() *NodeManagement_RemoveAllBindings_Call {
	return &NodeManagement_RemoveAllBindings_Call{Call: _e.mock.On("RemoveAllBindings")}
}

func (_c *NodeManagement_RemoveAllBindings_Call) Run(run func()) *NodeManagement_RemoveAllBindings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NodeManagement_RemoveAllBindings_Call) Return() *NodeManagement_RemoveAllBindings_Call {
	_c.Call.Return()
	return _c
}

func (_c *NodeManagement_RemoveAllBindings_Call) RunAndReturn(run func()) *NodeManagement_RemoveAllBindings_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAllSubscriptions provides a mock function with given fields:
func (_m *NodeManagement) RemoveAllSubscriptions() {
	_m.Called()
}

// NodeManagement_RemoveAllSubscriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAllSubscriptions'
type NodeManagement_RemoveAllSubscriptions_Call struct {
	*mock.Call
}

// RemoveAllSubscriptions is a helper method to define mock.On call
func (_e *NodeManagement_Expecter) RemoveAllSubscriptions() *NodeManagement_RemoveAllSubscriptions_Call {
	return &NodeManagement_RemoveAllSubscriptions_Call{Call: _e.mock.On("RemoveAllSubscriptions")}
}

func (_c *NodeManagement_RemoveAllSubscriptions_Call) Run(run func()) *NodeManagement_RemoveAllSubscriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NodeManagement_RemoveAllSubscriptions_Call) Return() *NodeManagement_RemoveAllSubscriptions_Call {
	_c.Call.Return()
	return _c
}

func (_c *NodeManagement_RemoveAllSubscriptions_Call) RunAndReturn(run func()) *NodeManagement_RemoveAllSubscriptions_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveBinding provides a mock function with given fields: remoteAddress
func (_m *NodeManagement) RemoveBinding(remoteAddress *model.FeatureAddressType) {
	_m.Called(remoteAddress)
}

// NodeManagement_RemoveBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveBinding'
type NodeManagement_RemoveBinding_Call struct {
	*mock.Call
}

// RemoveBinding is a helper method to define mock.On call
//   - remoteAddress *model.FeatureAddressType
func (_e *NodeManagement_Expecter) RemoveBinding(remoteAddress interface{}) *NodeManagement_RemoveBinding_Call {
	return &NodeManagement_RemoveBinding_Call{Call: _e.mock.On("RemoveBinding", remoteAddress)}
}

func (_c *NodeManagement_RemoveBinding_Call) Run(run func(remoteAddress *model.FeatureAddressType)) *NodeManagement_RemoveBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.FeatureAddressType))
	})
	return _c
}

func (_c *NodeManagement_RemoveBinding_Call) Return() *NodeManagement_RemoveBinding_Call {
	_c.Call.Return()
	return _c
}

func (_c *NodeManagement_RemoveBinding_Call) RunAndReturn(run func(*model.FeatureAddressType)) *NodeManagement_RemoveBinding_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveSubscription provides a mock function with given fields: remoteAddress
func (_m *NodeManagement) RemoveSubscription(remoteAddress *model.FeatureAddressType) {
	_m.Called(remoteAddress)
}

// NodeManagement_RemoveSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSubscription'
type NodeManagement_RemoveSubscription_Call struct {
	*mock.Call
}

// RemoveSubscription is a helper method to define mock.On call
//   - remoteAddress *model.FeatureAddressType
func (_e *NodeManagement_Expecter) RemoveSubscription(remoteAddress interface{}) *NodeManagement_RemoveSubscription_Call {
	return &NodeManagement_RemoveSubscription_Call{Call: _e.mock.On("RemoveSubscription", remoteAddress)}
}

func (_c *NodeManagement_RemoveSubscription_Call) Run(run func(remoteAddress *model.FeatureAddressType)) *NodeManagement_RemoveSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.FeatureAddressType))
	})
	return _c
}

func (_c *NodeManagement_RemoveSubscription_Call) Return() *NodeManagement_RemoveSubscription_Call {
	_c.Call.Return()
	return _c
}

func (_c *NodeManagement_RemoveSubscription_Call) RunAndReturn(run func(*model.FeatureAddressType)) *NodeManagement_RemoveSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// RequestData provides a mock function with given fields: function, selector, elements, destination
func (_m *NodeManagement) RequestData(function model.FunctionType, selector interface{}, elements interface{}, destination api.FeatureRemote) (*model.MsgCounterType, *model.ErrorType) {
	ret := _m.Called(function, selector, elements, destination)

	if len(ret) == 0 {
		panic("no return value specified for RequestData")
	}

	var r0 *model.MsgCounterType
	var r1 *model.ErrorType
	if rf, ok := ret.Get(0).(func(model.FunctionType, interface{}, interface{}, api.FeatureRemote) (*model.MsgCounterType, *model.ErrorType)); ok {
		return rf(function, selector, elements, destination)
	}
	if rf, ok := ret.Get(0).(func(model.FunctionType, interface{}, interface{}, api.FeatureRemote) *model.MsgCounterType); ok {
		r0 = rf(function, selector, elements, destination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}

	if rf, ok := ret.Get(1).(func(model.FunctionType, interface{}, interface{}, api.FeatureRemote) *model.ErrorType); ok {
		r1 = rf(function, selector, elements, destination)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.ErrorType)
		}
	}

	return r0, r1
}

// NodeManagement_RequestData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestData'
type NodeManagement_RequestData_Call struct {
	*mock.Call
}

// RequestData is a helper method to define mock.On call
//   - function model.FunctionType
//   - selector interface{}
//   - elements interface{}
//   - destination api.FeatureRemote
func (_e *NodeManagement_Expecter) RequestData(function interface{}, selector interface{}, elements interface{}, destination interface{}) *NodeManagement_RequestData_Call {
	return &NodeManagement_RequestData_Call{Call: _e.mock.On("RequestData", function, selector, elements, destination)}
}

func (_c *NodeManagement_RequestData_Call) Run(run func(function model.FunctionType, selector interface{}, elements interface{}, destination api.FeatureRemote)) *NodeManagement_RequestData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.FunctionType), args[1].(interface{}), args[2].(interface{}), args[3].(api.FeatureRemote))
	})
	return _c
}

func (_c *NodeManagement_RequestData_Call) Return(_a0 *model.MsgCounterType, _a1 *model.ErrorType) *NodeManagement_RequestData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NodeManagement_RequestData_Call) RunAndReturn(run func(model.FunctionType, interface{}, interface{}, api.FeatureRemote) (*model.MsgCounterType, *model.ErrorType)) *NodeManagement_RequestData_Call {
	_c.Call.Return(run)
	return _c
}

// RequestDataBySenderAddress provides a mock function with given fields: cmd, sender, destinationSki, destinationAddress, maxDelay
func (_m *NodeManagement) RequestDataBySenderAddress(cmd model.CmdType, sender api.Sender, destinationSki string, destinationAddress *model.FeatureAddressType, maxDelay time.Duration) (*model.MsgCounterType, *model.ErrorType) {
	ret := _m.Called(cmd, sender, destinationSki, destinationAddress, maxDelay)

	if len(ret) == 0 {
		panic("no return value specified for RequestDataBySenderAddress")
	}

	var r0 *model.MsgCounterType
	var r1 *model.ErrorType
	if rf, ok := ret.Get(0).(func(model.CmdType, api.Sender, string, *model.FeatureAddressType, time.Duration) (*model.MsgCounterType, *model.ErrorType)); ok {
		return rf(cmd, sender, destinationSki, destinationAddress, maxDelay)
	}
	if rf, ok := ret.Get(0).(func(model.CmdType, api.Sender, string, *model.FeatureAddressType, time.Duration) *model.MsgCounterType); ok {
		r0 = rf(cmd, sender, destinationSki, destinationAddress, maxDelay)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}

	if rf, ok := ret.Get(1).(func(model.CmdType, api.Sender, string, *model.FeatureAddressType, time.Duration) *model.ErrorType); ok {
		r1 = rf(cmd, sender, destinationSki, destinationAddress, maxDelay)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.ErrorType)
		}
	}

	return r0, r1
}

// NodeManagement_RequestDataBySenderAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestDataBySenderAddress'
type NodeManagement_RequestDataBySenderAddress_Call struct {
	*mock.Call
}

// RequestDataBySenderAddress is a helper method to define mock.On call
//   - cmd model.CmdType
//   - sender api.Sender
//   - destinationSki string
//   - destinationAddress *model.FeatureAddressType
//   - maxDelay time.Duration
func (_e *NodeManagement_Expecter) RequestDataBySenderAddress(cmd interface{}, sender interface{}, destinationSki interface{}, destinationAddress interface{}, maxDelay interface{}) *NodeManagement_RequestDataBySenderAddress_Call {
	return &NodeManagement_RequestDataBySenderAddress_Call{Call: _e.mock.On("RequestDataBySenderAddress", cmd, sender, destinationSki, destinationAddress, maxDelay)}
}

func (_c *NodeManagement_RequestDataBySenderAddress_Call) Run(run func(cmd model.CmdType, sender api.Sender, destinationSki string, destinationAddress *model.FeatureAddressType, maxDelay time.Duration)) *NodeManagement_RequestDataBySenderAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.CmdType), args[1].(api.Sender), args[2].(string), args[3].(*model.FeatureAddressType), args[4].(time.Duration))
	})
	return _c
}

func (_c *NodeManagement_RequestDataBySenderAddress_Call) Return(_a0 *model.MsgCounterType, _a1 *model.ErrorType) *NodeManagement_RequestDataBySenderAddress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NodeManagement_RequestDataBySenderAddress_Call) RunAndReturn(run func(model.CmdType, api.Sender, string, *model.FeatureAddressType, time.Duration) (*model.MsgCounterType, *model.ErrorType)) *NodeManagement_RequestDataBySenderAddress_Call {
	_c.Call.Return(run)
	return _c
}

// Role provides a mock function with given fields:
func (_m *NodeManagement) Role() model.RoleType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Role")
	}

	var r0 model.RoleType
	if rf, ok := ret.Get(0).(func() model.RoleType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.RoleType)
	}

	return r0
}

// NodeManagement_Role_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Role'
type NodeManagement_Role_Call struct {
	*mock.Call
}

// Role is a helper method to define mock.On call
func (_e *NodeManagement_Expecter) Role() *NodeManagement_Role_Call {
	return &NodeManagement_Role_Call{Call: _e.mock.On("Role")}
}

func (_c *NodeManagement_Role_Call) Run(run func()) *NodeManagement_Role_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NodeManagement_Role_Call) Return(_a0 model.RoleType) *NodeManagement_Role_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NodeManagement_Role_Call) RunAndReturn(run func() model.RoleType) *NodeManagement_Role_Call {
	_c.Call.Return(run)
	return _c
}

// SetData provides a mock function with given fields: function, data
func (_m *NodeManagement) SetData(function model.FunctionType, data interface{}) {
	_m.Called(function, data)
}

// NodeManagement_SetData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetData'
type NodeManagement_SetData_Call struct {
	*mock.Call
}

// SetData is a helper method to define mock.On call
//   - function model.FunctionType
//   - data interface{}
func (_e *NodeManagement_Expecter) SetData(function interface{}, data interface{}) *NodeManagement_SetData_Call {
	return &NodeManagement_SetData_Call{Call: _e.mock.On("SetData", function, data)}
}

func (_c *NodeManagement_SetData_Call) Run(run func(function model.FunctionType, data interface{})) *NodeManagement_SetData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.FunctionType), args[1].(interface{}))
	})
	return _c
}

func (_c *NodeManagement_SetData_Call) Return() *NodeManagement_SetData_Call {
	_c.Call.Return()
	return _c
}

func (_c *NodeManagement_SetData_Call) RunAndReturn(run func(model.FunctionType, interface{})) *NodeManagement_SetData_Call {
	_c.Call.Return(run)
	return _c
}

// SetDescription provides a mock function with given fields: desc
func (_m *NodeManagement) SetDescription(desc *model.DescriptionType) {
	_m.Called(desc)
}

// NodeManagement_SetDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDescription'
type NodeManagement_SetDescription_Call struct {
	*mock.Call
}

// SetDescription is a helper method to define mock.On call
//   - desc *model.DescriptionType
func (_e *NodeManagement_Expecter) SetDescription(desc interface{}) *NodeManagement_SetDescription_Call {
	return &NodeManagement_SetDescription_Call{Call: _e.mock.On("SetDescription", desc)}
}

func (_c *NodeManagement_SetDescription_Call) Run(run func(desc *model.DescriptionType)) *NodeManagement_SetDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.DescriptionType))
	})
	return _c
}

func (_c *NodeManagement_SetDescription_Call) Return() *NodeManagement_SetDescription_Call {
	_c.Call.Return()
	return _c
}

func (_c *NodeManagement_SetDescription_Call) RunAndReturn(run func(*model.DescriptionType)) *NodeManagement_SetDescription_Call {
	_c.Call.Return(run)
	return _c
}

// SetDescriptionString provides a mock function with given fields: s
func (_m *NodeManagement) SetDescriptionString(s string) {
	_m.Called(s)
}

// NodeManagement_SetDescriptionString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDescriptionString'
type NodeManagement_SetDescriptionString_Call struct {
	*mock.Call
}

// SetDescriptionString is a helper method to define mock.On call
//   - s string
func (_e *NodeManagement_Expecter) SetDescriptionString(s interface{}) *NodeManagement_SetDescriptionString_Call {
	return &NodeManagement_SetDescriptionString_Call{Call: _e.mock.On("SetDescriptionString", s)}
}

func (_c *NodeManagement_SetDescriptionString_Call) Run(run func(s string)) *NodeManagement_SetDescriptionString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *NodeManagement_SetDescriptionString_Call) Return() *NodeManagement_SetDescriptionString_Call {
	_c.Call.Return()
	return _c
}

func (_c *NodeManagement_SetDescriptionString_Call) RunAndReturn(run func(string)) *NodeManagement_SetDescriptionString_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with given fields:
func (_m *NodeManagement) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NodeManagement_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type NodeManagement_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *NodeManagement_Expecter) String() *NodeManagement_String_Call {
	return &NodeManagement_String_Call{Call: _e.mock.On("String")}
}

func (_c *NodeManagement_String_Call) Run(run func()) *NodeManagement_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NodeManagement_String_Call) Return(_a0 string) *NodeManagement_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NodeManagement_String_Call) RunAndReturn(run func() string) *NodeManagement_String_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: remoteAdress
func (_m *NodeManagement) Subscribe(remoteAdress *model.FeatureAddressType) (*model.MsgCounterType, *model.ErrorType) {
	ret := _m.Called(remoteAdress)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 *model.MsgCounterType
	var r1 *model.ErrorType
	if rf, ok := ret.Get(0).(func(*model.FeatureAddressType) (*model.MsgCounterType, *model.ErrorType)); ok {
		return rf(remoteAdress)
	}
	if rf, ok := ret.Get(0).(func(*model.FeatureAddressType) *model.MsgCounterType); ok {
		r0 = rf(remoteAdress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.FeatureAddressType) *model.ErrorType); ok {
		r1 = rf(remoteAdress)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.ErrorType)
		}
	}

	return r0, r1
}

// NodeManagement_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type NodeManagement_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - remoteAdress *model.FeatureAddressType
func (_e *NodeManagement_Expecter) Subscribe(remoteAdress interface{}) *NodeManagement_Subscribe_Call {
	return &NodeManagement_Subscribe_Call{Call: _e.mock.On("Subscribe", remoteAdress)}
}

func (_c *NodeManagement_Subscribe_Call) Run(run func(remoteAdress *model.FeatureAddressType)) *NodeManagement_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.FeatureAddressType))
	})
	return _c
}

func (_c *NodeManagement_Subscribe_Call) Return(_a0 *model.MsgCounterType, _a1 *model.ErrorType) *NodeManagement_Subscribe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NodeManagement_Subscribe_Call) RunAndReturn(run func(*model.FeatureAddressType) (*model.MsgCounterType, *model.ErrorType)) *NodeManagement_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function with given fields:
func (_m *NodeManagement) Type() model.FeatureTypeType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 model.FeatureTypeType
	if rf, ok := ret.Get(0).(func() model.FeatureTypeType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.FeatureTypeType)
	}

	return r0
}

// NodeManagement_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type NodeManagement_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *NodeManagement_Expecter) Type() *NodeManagement_Type_Call {
	return &NodeManagement_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *NodeManagement_Type_Call) Run(run func()) *NodeManagement_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NodeManagement_Type_Call) Return(_a0 model.FeatureTypeType) *NodeManagement_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NodeManagement_Type_Call) RunAndReturn(run func() model.FeatureTypeType) *NodeManagement_Type_Call {
	_c.Call.Return(run)
	return _c
}

// WriteData provides a mock function with given fields: function, deleteSelector, partialSelector, deleteElements, destination
func (_m *NodeManagement) WriteData(function model.FunctionType, deleteSelector interface{}, partialSelector interface{}, deleteElements interface{}, destination api.FeatureRemote) (*model.MsgCounterType, *model.ErrorType) {
	ret := _m.Called(function, deleteSelector, partialSelector, deleteElements, destination)

	if len(ret) == 0 {
		panic("no return value specified for WriteData")
	}

	var r0 *model.MsgCounterType
	var r1 *model.ErrorType
	if rf, ok := ret.Get(0).(func(model.FunctionType, interface{}, interface{}, interface{}, api.FeatureRemote) (*model.MsgCounterType, *model.ErrorType)); ok {
		return rf(function, deleteSelector, partialSelector, deleteElements, destination)
	}
	if rf, ok := ret.Get(0).(func(model.FunctionType, interface{}, interface{}, interface{}, api.FeatureRemote) *model.MsgCounterType); ok {
		r0 = rf(function, deleteSelector, partialSelector, deleteElements, destination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}

	if rf, ok := ret.Get(1).(func(model.FunctionType, interface{}, interface{}, interface{}, api.FeatureRemote) *model.ErrorType); ok {
		r1 = rf(function, deleteSelector, partialSelector, deleteElements, destination)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.ErrorType)
		}
	}

	return r0, r1
}

// NodeManagement_WriteData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteData'
type NodeManagement_WriteData_Call struct {
	*mock.Call
}

// WriteData is a helper method to define mock.On call
//   - function model.FunctionType
//   - deleteSelector interface{}
//   - partialSelector interface{}
//   - deleteElements interface{}
//   - destination api.FeatureRemote
func (_e *NodeManagement_Expecter) WriteData(function interface{}, deleteSelector interface{}, partialSelector interface{}, deleteElements interface{}, destination interface{}) *NodeManagement_WriteData_Call {
	return &NodeManagement_WriteData_Call{Call: _e.mock.On("WriteData", function, deleteSelector, partialSelector, deleteElements, destination)}
}

func (_c *NodeManagement_WriteData_Call) Run(run func(function model.FunctionType, deleteSelector interface{}, partialSelector interface{}, deleteElements interface{}, destination api.FeatureRemote)) *NodeManagement_WriteData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.FunctionType), args[1].(interface{}), args[2].(interface{}), args[3].(interface{}), args[4].(api.FeatureRemote))
	})
	return _c
}

func (_c *NodeManagement_WriteData_Call) Return(_a0 *model.MsgCounterType, _a1 *model.ErrorType) *NodeManagement_WriteData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NodeManagement_WriteData_Call) RunAndReturn(run func(model.FunctionType, interface{}, interface{}, interface{}, api.FeatureRemote) (*model.MsgCounterType, *model.ErrorType)) *NodeManagement_WriteData_Call {
	_c.Call.Return(run)
	return _c
}

// NewNodeManagement creates a new instance of NodeManagement. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodeManagement(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodeManagement {
	mock := &NodeManagement{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
