// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/spine-go/api"
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewSubscriptionManagerInterface creates a new instance of SubscriptionManagerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionManagerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionManagerInterface {
	mock := &SubscriptionManagerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SubscriptionManagerInterface is an autogenerated mock type for the SubscriptionManagerInterface type
type SubscriptionManagerInterface struct {
	mock.Mock
}

type SubscriptionManagerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *SubscriptionManagerInterface) EXPECT() *SubscriptionManagerInterface_Expecter {
	return &SubscriptionManagerInterface_Expecter{mock: &_m.Mock}
}

// AddSubscription provides a mock function for the type SubscriptionManagerInterface
func (_mock *SubscriptionManagerInterface) AddSubscription(remoteDevice api.DeviceRemoteInterface, data model.SubscriptionManagementRequestCallType) error {
	ret := _mock.Called(remoteDevice, data)

	if len(ret) == 0 {
		panic("no return value specified for AddSubscription")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(api.DeviceRemoteInterface, model.SubscriptionManagementRequestCallType) error); ok {
		r0 = returnFunc(remoteDevice, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionManagerInterface_AddSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSubscription'
type SubscriptionManagerInterface_AddSubscription_Call struct {
	*mock.Call
}

// AddSubscription is a helper method to define mock.On call
//   - remoteDevice api.DeviceRemoteInterface
//   - data model.SubscriptionManagementRequestCallType
func (_e *SubscriptionManagerInterface_Expecter) AddSubscription(remoteDevice interface{}, data interface{}) *SubscriptionManagerInterface_AddSubscription_Call {
	return &SubscriptionManagerInterface_AddSubscription_Call{Call: _e.mock.On("AddSubscription", remoteDevice, data)}
}

func (_c *SubscriptionManagerInterface_AddSubscription_Call) Run(run func(remoteDevice api.DeviceRemoteInterface, data model.SubscriptionManagementRequestCallType)) *SubscriptionManagerInterface_AddSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.DeviceRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.DeviceRemoteInterface)
		}
		var arg1 model.SubscriptionManagementRequestCallType
		if args[1] != nil {
			arg1 = args[1].(model.SubscriptionManagementRequestCallType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionManagerInterface_AddSubscription_Call) Return(err error) *SubscriptionManagerInterface_AddSubscription_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionManagerInterface_AddSubscription_Call) RunAndReturn(run func(remoteDevice api.DeviceRemoteInterface, data model.SubscriptionManagementRequestCallType) error) *SubscriptionManagerInterface_AddSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// HasSubscription provides a mock function for the type SubscriptionManagerInterface
func (_mock *SubscriptionManagerInterface) HasSubscription(clientAddress *model.FeatureAddressType, serverAddress *model.FeatureAddressType) bool {
	ret := _mock.Called(clientAddress, serverAddress)

	if len(ret) == 0 {
		panic("no return value specified for HasSubscription")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(*model.FeatureAddressType, *model.FeatureAddressType) bool); ok {
		r0 = returnFunc(clientAddress, serverAddress)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// SubscriptionManagerInterface_HasSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasSubscription'
type SubscriptionManagerInterface_HasSubscription_Call struct {
	*mock.Call
}

// HasSubscription is a helper method to define mock.On call
//   - clientAddress *model.FeatureAddressType
//   - serverAddress *model.FeatureAddressType
func (_e *SubscriptionManagerInterface_Expecter) HasSubscription(clientAddress interface{}, serverAddress interface{}) *SubscriptionManagerInterface_HasSubscription_Call {
	return &SubscriptionManagerInterface_HasSubscription_Call{Call: _e.mock.On("HasSubscription", clientAddress, serverAddress)}
}

func (_c *SubscriptionManagerInterface_HasSubscription_Call) Run(run func(clientAddress *model.FeatureAddressType, serverAddress *model.FeatureAddressType)) *SubscriptionManagerInterface_HasSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.FeatureAddressType
		if args[0] != nil {
			arg0 = args[0].(*model.FeatureAddressType)
		}
		var arg1 *model.FeatureAddressType
		if args[1] != nil {
			arg1 = args[1].(*model.FeatureAddressType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionManagerInterface_HasSubscription_Call) Return(b bool) *SubscriptionManagerInterface_HasSubscription_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *SubscriptionManagerInterface_HasSubscription_Call) RunAndReturn(run func(clientAddress *model.FeatureAddressType, serverAddress *model.FeatureAddressType) bool) *SubscriptionManagerInterface_HasSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveSubscription provides a mock function for the type SubscriptionManagerInterface
func (_mock *SubscriptionManagerInterface) RemoveSubscription(remoteDevice api.DeviceRemoteInterface, data model.SubscriptionManagementDeleteCallType) error {
	ret := _mock.Called(remoteDevice, data)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSubscription")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(api.DeviceRemoteInterface, model.SubscriptionManagementDeleteCallType) error); ok {
		r0 = returnFunc(remoteDevice, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionManagerInterface_RemoveSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSubscription'
type SubscriptionManagerInterface_RemoveSubscription_Call struct {
	*mock.Call
}

// RemoveSubscription is a helper method to define mock.On call
//   - remoteDevice api.DeviceRemoteInterface
//   - data model.SubscriptionManagementDeleteCallType
func (_e *SubscriptionManagerInterface_Expecter) RemoveSubscription(remoteDevice interface{}, data interface{}) *SubscriptionManagerInterface_RemoveSubscription_Call {
	return &SubscriptionManagerInterface_RemoveSubscription_Call{Call: _e.mock.On("RemoveSubscription", remoteDevice, data)}
}

func (_c *SubscriptionManagerInterface_RemoveSubscription_Call) Run(run func(remoteDevice api.DeviceRemoteInterface, data model.SubscriptionManagementDeleteCallType)) *SubscriptionManagerInterface_RemoveSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.DeviceRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.DeviceRemoteInterface)
		}
		var arg1 model.SubscriptionManagementDeleteCallType
		if args[1] != nil {
			arg1 = args[1].(model.SubscriptionManagementDeleteCallType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionManagerInterface_RemoveSubscription_Call) Return(err error) *SubscriptionManagerInterface_RemoveSubscription_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionManagerInterface_RemoveSubscription_Call) RunAndReturn(run func(remoteDevice api.DeviceRemoteInterface, data model.SubscriptionManagementDeleteCallType) error) *SubscriptionManagerInterface_RemoveSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveSubscriptionsForLocalEntity provides a mock function for the type SubscriptionManagerInterface
func (_mock *SubscriptionManagerInterface) RemoveSubscriptionsForLocalEntity(localEntity api.EntityLocalInterface) {
	_mock.Called(localEntity)
	return
}

// SubscriptionManagerInterface_RemoveSubscriptionsForLocalEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSubscriptionsForLocalEntity'
type SubscriptionManagerInterface_RemoveSubscriptionsForLocalEntity_Call struct {
	*mock.Call
}

// RemoveSubscriptionsForLocalEntity is a helper method to define mock.On call
//   - localEntity api.EntityLocalInterface
func (_e *SubscriptionManagerInterface_Expecter) RemoveSubscriptionsForLocalEntity(localEntity interface{}) *SubscriptionManagerInterface_RemoveSubscriptionsForLocalEntity_Call {
	return &SubscriptionManagerInterface_RemoveSubscriptionsForLocalEntity_Call{Call: _e.mock.On("RemoveSubscriptionsForLocalEntity", localEntity)}
}

func (_c *SubscriptionManagerInterface_RemoveSubscriptionsForLocalEntity_Call) Run(run func(localEntity api.EntityLocalInterface)) *SubscriptionManagerInterface_RemoveSubscriptionsForLocalEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityLocalInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityLocalInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubscriptionManagerInterface_RemoveSubscriptionsForLocalEntity_Call) Return() *SubscriptionManagerInterface_RemoveSubscriptionsForLocalEntity_Call {
	_c.Call.Return()
	return _c
}

func (_c *SubscriptionManagerInterface_RemoveSubscriptionsForLocalEntity_Call) RunAndReturn(run func(localEntity api.EntityLocalInterface)) *SubscriptionManagerInterface_RemoveSubscriptionsForLocalEntity_Call {
	_c.Run(run)
	return _c
}

// RemoveSubscriptionsForRemoteDevice provides a mock function for the type SubscriptionManagerInterface
func (_mock *SubscriptionManagerInterface) RemoveSubscriptionsForRemoteDevice(remoteDevice api.DeviceRemoteInterface) {
	_mock.Called(remoteDevice)
	return
}

// SubscriptionManagerInterface_RemoveSubscriptionsForRemoteDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSubscriptionsForRemoteDevice'
type SubscriptionManagerInterface_RemoveSubscriptionsForRemoteDevice_Call struct {
	*mock.Call
}

// RemoveSubscriptionsForRemoteDevice is a helper method to define mock.On call
//   - remoteDevice api.DeviceRemoteInterface
func (_e *SubscriptionManagerInterface_Expecter) RemoveSubscriptionsForRemoteDevice(remoteDevice interface{}) *SubscriptionManagerInterface_RemoveSubscriptionsForRemoteDevice_Call {
	return &SubscriptionManagerInterface_RemoveSubscriptionsForRemoteDevice_Call{Call: _e.mock.On("RemoveSubscriptionsForRemoteDevice", remoteDevice)}
}

func (_c *SubscriptionManagerInterface_RemoveSubscriptionsForRemoteDevice_Call) Run(run func(remoteDevice api.DeviceRemoteInterface)) *SubscriptionManagerInterface_RemoveSubscriptionsForRemoteDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.DeviceRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.DeviceRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubscriptionManagerInterface_RemoveSubscriptionsForRemoteDevice_Call) Return() *SubscriptionManagerInterface_RemoveSubscriptionsForRemoteDevice_Call {
	_c.Call.Return()
	return _c
}

func (_c *SubscriptionManagerInterface_RemoveSubscriptionsForRemoteDevice_Call) RunAndReturn(run func(remoteDevice api.DeviceRemoteInterface)) *SubscriptionManagerInterface_RemoveSubscriptionsForRemoteDevice_Call {
	_c.Run(run)
	return _c
}

// RemoveSubscriptionsForRemoteEntity provides a mock function for the type SubscriptionManagerInterface
func (_mock *SubscriptionManagerInterface) RemoveSubscriptionsForRemoteEntity(remoteEntity api.EntityRemoteInterface) {
	_mock.Called(remoteEntity)
	return
}

// SubscriptionManagerInterface_RemoveSubscriptionsForRemoteEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSubscriptionsForRemoteEntity'
type SubscriptionManagerInterface_RemoveSubscriptionsForRemoteEntity_Call struct {
	*mock.Call
}

// RemoveSubscriptionsForRemoteEntity is a helper method to define mock.On call
//   - remoteEntity api.EntityRemoteInterface
func (_e *SubscriptionManagerInterface_Expecter) RemoveSubscriptionsForRemoteEntity(remoteEntity interface{}) *SubscriptionManagerInterface_RemoveSubscriptionsForRemoteEntity_Call {
	return &SubscriptionManagerInterface_RemoveSubscriptionsForRemoteEntity_Call{Call: _e.mock.On("RemoveSubscriptionsForRemoteEntity", remoteEntity)}
}

func (_c *SubscriptionManagerInterface_RemoveSubscriptionsForRemoteEntity_Call) Run(run func(remoteEntity api.EntityRemoteInterface)) *SubscriptionManagerInterface_RemoveSubscriptionsForRemoteEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubscriptionManagerInterface_RemoveSubscriptionsForRemoteEntity_Call) Return() *SubscriptionManagerInterface_RemoveSubscriptionsForRemoteEntity_Call {
	_c.Call.Return()
	return _c
}

func (_c *SubscriptionManagerInterface_RemoveSubscriptionsForRemoteEntity_Call) RunAndReturn(run func(remoteEntity api.EntityRemoteInterface)) *SubscriptionManagerInterface_RemoveSubscriptionsForRemoteEntity_Call {
	_c.Run(run)
	return _c
}

// SubscriptionsForFeatureAddress provides a mock function for the type SubscriptionManagerInterface
func (_mock *SubscriptionManagerInterface) SubscriptionsForFeatureAddress(localAddress model.FeatureAddressType) []model.SubscriptionManagementEntryDataType {
	ret := _mock.Called(localAddress)

	if len(ret) == 0 {
		panic("no return value specified for SubscriptionsForFeatureAddress")
	}

	var r0 []model.SubscriptionManagementEntryDataType
	if returnFunc, ok := ret.Get(0).(func(model.FeatureAddressType) []model.SubscriptionManagementEntryDataType); ok {
		r0 = returnFunc(localAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SubscriptionManagementEntryDataType)
		}
	}
	return r0
}

// SubscriptionManagerInterface_SubscriptionsForFeatureAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscriptionsForFeatureAddress'
type SubscriptionManagerInterface_SubscriptionsForFeatureAddress_Call struct {
	*mock.Call
}

// SubscriptionsForFeatureAddress is a helper method to define mock.On call
//   - localAddress model.FeatureAddressType
func (_e *SubscriptionManagerInterface_Expecter) SubscriptionsForFeatureAddress(localAddress interface{}) *SubscriptionManagerInterface_SubscriptionsForFeatureAddress_Call {
	return &SubscriptionManagerInterface_SubscriptionsForFeatureAddress_Call{Call: _e.mock.On("SubscriptionsForFeatureAddress", localAddress)}
}

func (_c *SubscriptionManagerInterface_SubscriptionsForFeatureAddress_Call) Run(run func(localAddress model.FeatureAddressType)) *SubscriptionManagerInterface_SubscriptionsForFeatureAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.FeatureAddressType
		if args[0] != nil {
			arg0 = args[0].(model.FeatureAddressType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubscriptionManagerInterface_SubscriptionsForFeatureAddress_Call) Return(subscriptionManagementEntryDataTypes []model.SubscriptionManagementEntryDataType) *SubscriptionManagerInterface_SubscriptionsForFeatureAddress_Call {
	_c.Call.Return(subscriptionManagementEntryDataTypes)
	return _c
}

func (_c *SubscriptionManagerInterface_SubscriptionsForFeatureAddress_Call) RunAndReturn(run func(localAddress model.FeatureAddressType) []model.SubscriptionManagementEntryDataType) *SubscriptionManagerInterface_SubscriptionsForFeatureAddress_Call {
	_c.Call.Return(run)
	return _c
}

// SubscriptionsForRemoteDevice provides a mock function for the type SubscriptionManagerInterface
func (_mock *SubscriptionManagerInterface) SubscriptionsForRemoteDevice(remoteDevice api.DeviceRemoteInterface) []model.SubscriptionManagementEntryDataType {
	ret := _mock.Called(remoteDevice)

	if len(ret) == 0 {
		panic("no return value specified for SubscriptionsForRemoteDevice")
	}

	var r0 []model.SubscriptionManagementEntryDataType
	if returnFunc, ok := ret.Get(0).(func(api.DeviceRemoteInterface) []model.SubscriptionManagementEntryDataType); ok {
		r0 = returnFunc(remoteDevice)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SubscriptionManagementEntryDataType)
		}
	}
	return r0
}

// SubscriptionManagerInterface_SubscriptionsForRemoteDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscriptionsForRemoteDevice'
type SubscriptionManagerInterface_SubscriptionsForRemoteDevice_Call struct {
	*mock.Call
}

// SubscriptionsForRemoteDevice is a helper method to define mock.On call
//   - remoteDevice api.DeviceRemoteInterface
func (_e *SubscriptionManagerInterface_Expecter) SubscriptionsForRemoteDevice(remoteDevice interface{}) *SubscriptionManagerInterface_SubscriptionsForRemoteDevice_Call {
	return &SubscriptionManagerInterface_SubscriptionsForRemoteDevice_Call{Call: _e.mock.On("SubscriptionsForRemoteDevice", remoteDevice)}
}

func (_c *SubscriptionManagerInterface_SubscriptionsForRemoteDevice_Call) Run(run func(remoteDevice api.DeviceRemoteInterface)) *SubscriptionManagerInterface_SubscriptionsForRemoteDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.DeviceRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.DeviceRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubscriptionManagerInterface_SubscriptionsForRemoteDevice_Call) Return(subscriptionManagementEntryDataTypes []model.SubscriptionManagementEntryDataType) *SubscriptionManagerInterface_SubscriptionsForRemoteDevice_Call {
	_c.Call.Return(subscriptionManagementEntryDataTypes)
	return _c
}

func (_c *SubscriptionManagerInterface_SubscriptionsForRemoteDevice_Call) RunAndReturn(run func(remoteDevice api.DeviceRemoteInterface) []model.SubscriptionManagementEntryDataType) *SubscriptionManagerInterface_SubscriptionsForRemoteDevice_Call {
	_c.Call.Return(run)
	return _c
}
